// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enums.proto

package protocol;

public final class EnumProtos {
  private EnumProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code ColourProto}
   */
  public enum ColourProto
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>RED = 1;</code>
     */
    RED(0, 1),
    /**
     * <code>BLUE = 2;</code>
     */
    BLUE(1, 2),
    /**
     * <code>ORANGE = 3;</code>
     */
    ORANGE(2, 3),
    /**
     * <code>WHITE = 4;</code>
     */
    WHITE(3, 4),
    ;

    /**
     * <code>RED = 1;</code>
     */
    public static final int RED_VALUE = 1;
    /**
     * <code>BLUE = 2;</code>
     */
    public static final int BLUE_VALUE = 2;
    /**
     * <code>ORANGE = 3;</code>
     */
    public static final int ORANGE_VALUE = 3;
    /**
     * <code>WHITE = 4;</code>
     */
    public static final int WHITE_VALUE = 4;


    public final int getNumber() { return value; }

    public static ColourProto valueOf(int value) {
      switch (value) {
        case 1: return RED;
        case 2: return BLUE;
        case 3: return ORANGE;
        case 4: return WHITE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ColourProto>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ColourProto>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ColourProto>() {
            public ColourProto findValueByNumber(int number) {
              return ColourProto.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protocol.EnumProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final ColourProto[] VALUES = values();

    public static ColourProto valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ColourProto(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ColourProto)
  }

  /**
   * Protobuf enum {@code ResourceTypeProto}
   */
  public enum ResourceTypeProto
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BRICK = 1;</code>
     */
    BRICK(0, 1),
    /**
     * <code>LUMBER = 2;</code>
     */
    LUMBER(1, 2),
    /**
     * <code>WOOL = 3;</code>
     */
    WOOL(2, 3),
    /**
     * <code>GRAIN = 4;</code>
     */
    GRAIN(3, 4),
    /**
     * <code>ORE = 5;</code>
     */
    ORE(4, 5),
    /**
     * <code>GENERIC = 6;</code>
     *
     * <pre>
     * useful within the context of defining a generic port 
     * </pre>
     */
    GENERIC(5, 6),
    ;

    /**
     * <code>BRICK = 1;</code>
     */
    public static final int BRICK_VALUE = 1;
    /**
     * <code>LUMBER = 2;</code>
     */
    public static final int LUMBER_VALUE = 2;
    /**
     * <code>WOOL = 3;</code>
     */
    public static final int WOOL_VALUE = 3;
    /**
     * <code>GRAIN = 4;</code>
     */
    public static final int GRAIN_VALUE = 4;
    /**
     * <code>ORE = 5;</code>
     */
    public static final int ORE_VALUE = 5;
    /**
     * <code>GENERIC = 6;</code>
     *
     * <pre>
     * useful within the context of defining a generic port 
     * </pre>
     */
    public static final int GENERIC_VALUE = 6;


    public final int getNumber() { return value; }

    public static ResourceTypeProto valueOf(int value) {
      switch (value) {
        case 1: return BRICK;
        case 2: return LUMBER;
        case 3: return WOOL;
        case 4: return GRAIN;
        case 5: return ORE;
        case 6: return GENERIC;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResourceTypeProto>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ResourceTypeProto>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResourceTypeProto>() {
            public ResourceTypeProto findValueByNumber(int number) {
              return ResourceTypeProto.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protocol.EnumProtos.getDescriptor().getEnumTypes().get(1);
    }

    private static final ResourceTypeProto[] VALUES = values();

    public static ResourceTypeProto valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ResourceTypeProto(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ResourceTypeProto)
  }

  /**
   * Protobuf enum {@code BuildingTypeProto}
   */
  public enum BuildingTypeProto
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SETTLEMENT = 1;</code>
     */
    SETTLEMENT(0, 1),
    /**
     * <code>CITY = 2;</code>
     */
    CITY(1, 2),
    ;

    /**
     * <code>SETTLEMENT = 1;</code>
     */
    public static final int SETTLEMENT_VALUE = 1;
    /**
     * <code>CITY = 2;</code>
     */
    public static final int CITY_VALUE = 2;


    public final int getNumber() { return value; }

    public static BuildingTypeProto valueOf(int value) {
      switch (value) {
        case 1: return SETTLEMENT;
        case 2: return CITY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BuildingTypeProto>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<BuildingTypeProto>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BuildingTypeProto>() {
            public BuildingTypeProto findValueByNumber(int number) {
              return BuildingTypeProto.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protocol.EnumProtos.getDescriptor().getEnumTypes().get(2);
    }

    private static final BuildingTypeProto[] VALUES = values();

    public static BuildingTypeProto valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private BuildingTypeProto(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:BuildingTypeProto)
  }

  /**
   * Protobuf enum {@code DevelopmentCardProto}
   */
  public enum DevelopmentCardProto
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>KNIGHT = 1;</code>
     */
    KNIGHT(0, 1),
    /**
     * <code>ROAD_BUILDING = 2;</code>
     */
    ROAD_BUILDING(1, 2),
    /**
     * <code>MONOPOLY = 3;</code>
     */
    MONOPOLY(2, 3),
    /**
     * <code>YEAR_OF_PLENTY = 4;</code>
     */
    YEAR_OF_PLENTY(3, 4),
    /**
     * <code>LIBRARY = 5;</code>
     */
    LIBRARY(4, 5),
    /**
     * <code>UNIVERSITY = 69;</code>
     *
     * <pre>
     *PALACE = 7;
     *MARKET = 8;
     *CHAPEL = 9;
     * </pre>
     */
    UNIVERSITY(5, 69),
    ;

    /**
     * <code>KNIGHT = 1;</code>
     */
    public static final int KNIGHT_VALUE = 1;
    /**
     * <code>ROAD_BUILDING = 2;</code>
     */
    public static final int ROAD_BUILDING_VALUE = 2;
    /**
     * <code>MONOPOLY = 3;</code>
     */
    public static final int MONOPOLY_VALUE = 3;
    /**
     * <code>YEAR_OF_PLENTY = 4;</code>
     */
    public static final int YEAR_OF_PLENTY_VALUE = 4;
    /**
     * <code>LIBRARY = 5;</code>
     */
    public static final int LIBRARY_VALUE = 5;
    /**
     * <code>UNIVERSITY = 69;</code>
     *
     * <pre>
     *PALACE = 7;
     *MARKET = 8;
     *CHAPEL = 9;
     * </pre>
     */
    public static final int UNIVERSITY_VALUE = 69;


    public final int getNumber() { return value; }

    public static DevelopmentCardProto valueOf(int value) {
      switch (value) {
        case 1: return KNIGHT;
        case 2: return ROAD_BUILDING;
        case 3: return MONOPOLY;
        case 4: return YEAR_OF_PLENTY;
        case 5: return LIBRARY;
        case 69: return UNIVERSITY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DevelopmentCardProto>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<DevelopmentCardProto>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DevelopmentCardProto>() {
            public DevelopmentCardProto findValueByNumber(int number) {
              return DevelopmentCardProto.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protocol.EnumProtos.getDescriptor().getEnumTypes().get(3);
    }

    private static final DevelopmentCardProto[] VALUES = values();

    public static DevelopmentCardProto valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private DevelopmentCardProto(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:DevelopmentCardProto)
  }

  /**
   * Protobuf enum {@code TradeStatusProto}
   */
  public enum TradeStatusProto
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ACCEPT = 1;</code>
     */
    ACCEPT(0, 1),
    /**
     * <code>REJECT = 2;</code>
     */
    REJECT(1, 2),
    ;

    /**
     * <code>ACCEPT = 1;</code>
     */
    public static final int ACCEPT_VALUE = 1;
    /**
     * <code>REJECT = 2;</code>
     */
    public static final int REJECT_VALUE = 2;


    public final int getNumber() { return value; }

    public static TradeStatusProto valueOf(int value) {
      switch (value) {
        case 1: return ACCEPT;
        case 2: return REJECT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TradeStatusProto>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TradeStatusProto>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TradeStatusProto>() {
            public TradeStatusProto findValueByNumber(int number) {
              return TradeStatusProto.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protocol.EnumProtos.getDescriptor().getEnumTypes().get(4);
    }

    private static final TradeStatusProto[] VALUES = values();

    public static TradeStatusProto valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TradeStatusProto(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:TradeStatusProto)
  }

  /**
   * Protobuf enum {@code ResultProto}
   */
  public enum ResultProto
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SUCCESS = 1;</code>
     */
    SUCCESS(0, 1),
    /**
     * <code>FAILURE = 2;</code>
     */
    FAILURE(1, 2),
    ;

    /**
     * <code>SUCCESS = 1;</code>
     */
    public static final int SUCCESS_VALUE = 1;
    /**
     * <code>FAILURE = 2;</code>
     */
    public static final int FAILURE_VALUE = 2;


    public final int getNumber() { return value; }

    public static ResultProto valueOf(int value) {
      switch (value) {
        case 1: return SUCCESS;
        case 2: return FAILURE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResultProto>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ResultProto>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResultProto>() {
            public ResultProto findValueByNumber(int number) {
              return ResultProto.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protocol.EnumProtos.getDescriptor().getEnumTypes().get(5);
    }

    private static final ResultProto[] VALUES = values();

    public static ResultProto valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ResultProto(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ResultProto)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013enums.proto*7\n\013ColourProto\022\007\n\003RED\020\001\022\010\n" +
      "\004BLUE\020\002\022\n\n\006ORANGE\020\003\022\t\n\005WHITE\020\004*U\n\021Resour" +
      "ceTypeProto\022\t\n\005BRICK\020\001\022\n\n\006LUMBER\020\002\022\010\n\004WO" +
      "OL\020\003\022\t\n\005GRAIN\020\004\022\007\n\003ORE\020\005\022\013\n\007GENERIC\020\006*-\n" +
      "\021BuildingTypeProto\022\016\n\nSETTLEMENT\020\001\022\010\n\004CI" +
      "TY\020\002*t\n\024DevelopmentCardProto\022\n\n\006KNIGHT\020\001" +
      "\022\021\n\rROAD_BUILDING\020\002\022\014\n\010MONOPOLY\020\003\022\022\n\016YEA" +
      "R_OF_PLENTY\020\004\022\013\n\007LIBRARY\020\005\022\016\n\nUNIVERSITY" +
      "\020E**\n\020TradeStatusProto\022\n\n\006ACCEPT\020\001\022\n\n\006RE" +
      "JECT\020\002*\'\n\013ResultProto\022\013\n\007SUCCESS\020\001\022\013\n\007FA",
      "ILURE\020\002B\026\n\010protocolB\nEnumProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
