// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package protocol;

public final class MessageProtos {
  private MessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .ColourProto playerColour = 1;</code>
     */
    boolean hasPlayerColour();
    /**
     * <code>required .ColourProto playerColour = 1;</code>
     */
    protocol.EnumProtos.ColourProto getPlayerColour();

    /**
     * <code>optional .Request request = 2;</code>
     */
    boolean hasRequest();
    /**
     * <code>optional .Request request = 2;</code>
     */
    protocol.RequestProtos.Request getRequest();
    /**
     * <code>optional .Request request = 2;</code>
     */
    protocol.RequestProtos.RequestOrBuilder getRequestOrBuilder();

    /**
     * <code>optional .Response response = 3;</code>
     */
    boolean hasResponse();
    /**
     * <code>optional .Response response = 3;</code>
     */
    protocol.ResponseProtos.Response getResponse();
    /**
     * <code>optional .Response response = 3;</code>
     */
    protocol.ResponseProtos.ResponseOrBuilder getResponseOrBuilder();

    /**
     * <code>optional .Event event = 4;</code>
     */
    boolean hasEvent();
    /**
     * <code>optional .Event event = 4;</code>
     */
    protocol.EventProtos.Event getEvent();
    /**
     * <code>optional .Event event = 4;</code>
     */
    protocol.EventProtos.EventOrBuilder getEventOrBuilder();
  }
  /**
   * Protobuf type {@code Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Message(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }

    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              protocol.EnumProtos.ColourProto value = protocol.EnumProtos.ColourProto.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                playerColour_ = value;
              }
              break;
            }
            case 18: {
              protocol.RequestProtos.Request.Builder subBuilder = null;
              if (typeCase_ == 2) {
                subBuilder = ((protocol.RequestProtos.Request) type_).toBuilder();
              }
              type_ = input.readMessage(protocol.RequestProtos.Request.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((protocol.RequestProtos.Request) type_);
                type_ = subBuilder.buildPartial();
              }
              typeCase_ = 2;
              break;
            }
            case 26: {
              protocol.ResponseProtos.Response.Builder subBuilder = null;
              if (typeCase_ == 3) {
                subBuilder = ((protocol.ResponseProtos.Response) type_).toBuilder();
              }
              type_ = input.readMessage(protocol.ResponseProtos.Response.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((protocol.ResponseProtos.Response) type_);
                type_ = subBuilder.buildPartial();
              }
              typeCase_ = 3;
              break;
            }
            case 34: {
              protocol.EventProtos.Event.Builder subBuilder = null;
              if (typeCase_ == 4) {
                subBuilder = ((protocol.EventProtos.Event) type_).toBuilder();
              }
              type_ = input.readMessage(protocol.EventProtos.Event.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((protocol.EventProtos.Event) type_);
                type_ = subBuilder.buildPartial();
              }
              typeCase_ = 4;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.MessageProtos.internal_static_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.MessageProtos.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.MessageProtos.Message.class, protocol.MessageProtos.Message.Builder.class);
    }

    public static com.google.protobuf.Parser<Message> PARSER =
        new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    private int typeCase_ = 0;
    private java.lang.Object type_;
    public enum TypeCase
        implements com.google.protobuf.Internal.EnumLite {
      REQUEST(2),
      RESPONSE(3),
      EVENT(4),
      TYPE_NOT_SET(0);
      private int value = 0;
      private TypeCase(int value) {
        this.value = value;
      }
      public static TypeCase valueOf(int value) {
        switch (value) {
          case 2: return REQUEST;
          case 3: return RESPONSE;
          case 4: return EVENT;
          case 0: return TYPE_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public TypeCase
    getTypeCase() {
      return TypeCase.valueOf(
          typeCase_);
    }

    public static final int PLAYERCOLOUR_FIELD_NUMBER = 1;
    private protocol.EnumProtos.ColourProto playerColour_;
    /**
     * <code>required .ColourProto playerColour = 1;</code>
     */
    public boolean hasPlayerColour() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .ColourProto playerColour = 1;</code>
     */
    public protocol.EnumProtos.ColourProto getPlayerColour() {
      return playerColour_;
    }

    public static final int REQUEST_FIELD_NUMBER = 2;
    /**
     * <code>optional .Request request = 2;</code>
     */
    public boolean hasRequest() {
      return typeCase_ == 2;
    }
    /**
     * <code>optional .Request request = 2;</code>
     */
    public protocol.RequestProtos.Request getRequest() {
      if (typeCase_ == 2) {
         return (protocol.RequestProtos.Request) type_;
      }
      return protocol.RequestProtos.Request.getDefaultInstance();
    }
    /**
     * <code>optional .Request request = 2;</code>
     */
    public protocol.RequestProtos.RequestOrBuilder getRequestOrBuilder() {
      if (typeCase_ == 2) {
         return (protocol.RequestProtos.Request) type_;
      }
      return protocol.RequestProtos.Request.getDefaultInstance();
    }

    public static final int RESPONSE_FIELD_NUMBER = 3;
    /**
     * <code>optional .Response response = 3;</code>
     */
    public boolean hasResponse() {
      return typeCase_ == 3;
    }
    /**
     * <code>optional .Response response = 3;</code>
     */
    public protocol.ResponseProtos.Response getResponse() {
      if (typeCase_ == 3) {
         return (protocol.ResponseProtos.Response) type_;
      }
      return protocol.ResponseProtos.Response.getDefaultInstance();
    }
    /**
     * <code>optional .Response response = 3;</code>
     */
    public protocol.ResponseProtos.ResponseOrBuilder getResponseOrBuilder() {
      if (typeCase_ == 3) {
         return (protocol.ResponseProtos.Response) type_;
      }
      return protocol.ResponseProtos.Response.getDefaultInstance();
    }

    public static final int EVENT_FIELD_NUMBER = 4;
    /**
     * <code>optional .Event event = 4;</code>
     */
    public boolean hasEvent() {
      return typeCase_ == 4;
    }
    /**
     * <code>optional .Event event = 4;</code>
     */
    public protocol.EventProtos.Event getEvent() {
      if (typeCase_ == 4) {
         return (protocol.EventProtos.Event) type_;
      }
      return protocol.EventProtos.Event.getDefaultInstance();
    }
    /**
     * <code>optional .Event event = 4;</code>
     */
    public protocol.EventProtos.EventOrBuilder getEventOrBuilder() {
      if (typeCase_ == 4) {
         return (protocol.EventProtos.Event) type_;
      }
      return protocol.EventProtos.Event.getDefaultInstance();
    }

    private void initFields() {
      playerColour_ = protocol.EnumProtos.ColourProto.RED;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPlayerColour()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasRequest()) {
        if (!getRequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasResponse()) {
        if (!getResponse().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasEvent()) {
        if (!getEvent().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, playerColour_.getNumber());
      }
      if (typeCase_ == 2) {
        output.writeMessage(2, (protocol.RequestProtos.Request) type_);
      }
      if (typeCase_ == 3) {
        output.writeMessage(3, (protocol.ResponseProtos.Response) type_);
      }
      if (typeCase_ == 4) {
        output.writeMessage(4, (protocol.EventProtos.Event) type_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, playerColour_.getNumber());
      }
      if (typeCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (protocol.RequestProtos.Request) type_);
      }
      if (typeCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (protocol.ResponseProtos.Response) type_);
      }
      if (typeCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (protocol.EventProtos.Event) type_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protocol.MessageProtos.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.MessageProtos.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.MessageProtos.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.MessageProtos.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.MessageProtos.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.MessageProtos.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol.MessageProtos.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol.MessageProtos.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol.MessageProtos.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.MessageProtos.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocol.MessageProtos.Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        protocol.MessageProtos.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.MessageProtos.internal_static_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.MessageProtos.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.MessageProtos.Message.class, protocol.MessageProtos.Message.Builder.class);
      }

      // Construct using protocol.MessageProtos.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        playerColour_ = protocol.EnumProtos.ColourProto.RED;
        bitField0_ = (bitField0_ & ~0x00000001);
        typeCase_ = 0;
        type_ = null;
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.MessageProtos.internal_static_Message_descriptor;
      }

      public protocol.MessageProtos.Message getDefaultInstanceForType() {
        return protocol.MessageProtos.Message.getDefaultInstance();
      }

      public protocol.MessageProtos.Message build() {
        protocol.MessageProtos.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.MessageProtos.Message buildPartial() {
        protocol.MessageProtos.Message result = new protocol.MessageProtos.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerColour_ = playerColour_;
        if (typeCase_ == 2) {
          if (requestBuilder_ == null) {
            result.type_ = type_;
          } else {
            result.type_ = requestBuilder_.build();
          }
        }
        if (typeCase_ == 3) {
          if (responseBuilder_ == null) {
            result.type_ = type_;
          } else {
            result.type_ = responseBuilder_.build();
          }
        }
        if (typeCase_ == 4) {
          if (eventBuilder_ == null) {
            result.type_ = type_;
          } else {
            result.type_ = eventBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.typeCase_ = typeCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.MessageProtos.Message) {
          return mergeFrom((protocol.MessageProtos.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.MessageProtos.Message other) {
        if (other == protocol.MessageProtos.Message.getDefaultInstance()) return this;
        if (other.hasPlayerColour()) {
          setPlayerColour(other.getPlayerColour());
        }
        switch (other.getTypeCase()) {
          case REQUEST: {
            mergeRequest(other.getRequest());
            break;
          }
          case RESPONSE: {
            mergeResponse(other.getResponse());
            break;
          }
          case EVENT: {
            mergeEvent(other.getEvent());
            break;
          }
          case TYPE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPlayerColour()) {
          
          return false;
        }
        if (hasRequest()) {
          if (!getRequest().isInitialized()) {
            
            return false;
          }
        }
        if (hasResponse()) {
          if (!getResponse().isInitialized()) {
            
            return false;
          }
        }
        if (hasEvent()) {
          if (!getEvent().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.MessageProtos.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.MessageProtos.Message) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int typeCase_ = 0;
      private java.lang.Object type_;
      public TypeCase
          getTypeCase() {
        return TypeCase.valueOf(
            typeCase_);
      }

      public Builder clearType() {
        typeCase_ = 0;
        type_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private protocol.EnumProtos.ColourProto playerColour_ = protocol.EnumProtos.ColourProto.RED;
      /**
       * <code>required .ColourProto playerColour = 1;</code>
       */
      public boolean hasPlayerColour() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .ColourProto playerColour = 1;</code>
       */
      public protocol.EnumProtos.ColourProto getPlayerColour() {
        return playerColour_;
      }
      /**
       * <code>required .ColourProto playerColour = 1;</code>
       */
      public Builder setPlayerColour(protocol.EnumProtos.ColourProto value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        playerColour_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .ColourProto playerColour = 1;</code>
       */
      public Builder clearPlayerColour() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerColour_ = protocol.EnumProtos.ColourProto.RED;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilder<
          protocol.RequestProtos.Request, protocol.RequestProtos.Request.Builder, protocol.RequestProtos.RequestOrBuilder> requestBuilder_;
      /**
       * <code>optional .Request request = 2;</code>
       */
      public boolean hasRequest() {
        return typeCase_ == 2;
      }
      /**
       * <code>optional .Request request = 2;</code>
       */
      public protocol.RequestProtos.Request getRequest() {
        if (requestBuilder_ == null) {
          if (typeCase_ == 2) {
            return (protocol.RequestProtos.Request) type_;
          }
          return protocol.RequestProtos.Request.getDefaultInstance();
        } else {
          if (typeCase_ == 2) {
            return requestBuilder_.getMessage();
          }
          return protocol.RequestProtos.Request.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Request request = 2;</code>
       */
      public Builder setRequest(protocol.RequestProtos.Request value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          type_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }
        typeCase_ = 2;
        return this;
      }
      /**
       * <code>optional .Request request = 2;</code>
       */
      public Builder setRequest(
          protocol.RequestProtos.Request.Builder builderForValue) {
        if (requestBuilder_ == null) {
          type_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }
        typeCase_ = 2;
        return this;
      }
      /**
       * <code>optional .Request request = 2;</code>
       */
      public Builder mergeRequest(protocol.RequestProtos.Request value) {
        if (requestBuilder_ == null) {
          if (typeCase_ == 2 &&
              type_ != protocol.RequestProtos.Request.getDefaultInstance()) {
            type_ = protocol.RequestProtos.Request.newBuilder((protocol.RequestProtos.Request) type_)
                .mergeFrom(value).buildPartial();
          } else {
            type_ = value;
          }
          onChanged();
        } else {
          if (typeCase_ == 2) {
            requestBuilder_.mergeFrom(value);
          }
          requestBuilder_.setMessage(value);
        }
        typeCase_ = 2;
        return this;
      }
      /**
       * <code>optional .Request request = 2;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          if (typeCase_ == 2) {
            typeCase_ = 0;
            type_ = null;
            onChanged();
          }
        } else {
          if (typeCase_ == 2) {
            typeCase_ = 0;
            type_ = null;
          }
          requestBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .Request request = 2;</code>
       */
      public protocol.RequestProtos.Request.Builder getRequestBuilder() {
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Request request = 2;</code>
       */
      public protocol.RequestProtos.RequestOrBuilder getRequestOrBuilder() {
        if ((typeCase_ == 2) && (requestBuilder_ != null)) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          if (typeCase_ == 2) {
            return (protocol.RequestProtos.Request) type_;
          }
          return protocol.RequestProtos.Request.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Request request = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          protocol.RequestProtos.Request, protocol.RequestProtos.Request.Builder, protocol.RequestProtos.RequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          if (!(typeCase_ == 2)) {
            type_ = protocol.RequestProtos.Request.getDefaultInstance();
          }
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              protocol.RequestProtos.Request, protocol.RequestProtos.Request.Builder, protocol.RequestProtos.RequestOrBuilder>(
                  (protocol.RequestProtos.Request) type_,
                  getParentForChildren(),
                  isClean());
          type_ = null;
        }
        typeCase_ = 2;
        return requestBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          protocol.ResponseProtos.Response, protocol.ResponseProtos.Response.Builder, protocol.ResponseProtos.ResponseOrBuilder> responseBuilder_;
      /**
       * <code>optional .Response response = 3;</code>
       */
      public boolean hasResponse() {
        return typeCase_ == 3;
      }
      /**
       * <code>optional .Response response = 3;</code>
       */
      public protocol.ResponseProtos.Response getResponse() {
        if (responseBuilder_ == null) {
          if (typeCase_ == 3) {
            return (protocol.ResponseProtos.Response) type_;
          }
          return protocol.ResponseProtos.Response.getDefaultInstance();
        } else {
          if (typeCase_ == 3) {
            return responseBuilder_.getMessage();
          }
          return protocol.ResponseProtos.Response.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Response response = 3;</code>
       */
      public Builder setResponse(protocol.ResponseProtos.Response value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          type_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }
        typeCase_ = 3;
        return this;
      }
      /**
       * <code>optional .Response response = 3;</code>
       */
      public Builder setResponse(
          protocol.ResponseProtos.Response.Builder builderForValue) {
        if (responseBuilder_ == null) {
          type_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }
        typeCase_ = 3;
        return this;
      }
      /**
       * <code>optional .Response response = 3;</code>
       */
      public Builder mergeResponse(protocol.ResponseProtos.Response value) {
        if (responseBuilder_ == null) {
          if (typeCase_ == 3 &&
              type_ != protocol.ResponseProtos.Response.getDefaultInstance()) {
            type_ = protocol.ResponseProtos.Response.newBuilder((protocol.ResponseProtos.Response) type_)
                .mergeFrom(value).buildPartial();
          } else {
            type_ = value;
          }
          onChanged();
        } else {
          if (typeCase_ == 3) {
            responseBuilder_.mergeFrom(value);
          }
          responseBuilder_.setMessage(value);
        }
        typeCase_ = 3;
        return this;
      }
      /**
       * <code>optional .Response response = 3;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          if (typeCase_ == 3) {
            typeCase_ = 0;
            type_ = null;
            onChanged();
          }
        } else {
          if (typeCase_ == 3) {
            typeCase_ = 0;
            type_ = null;
          }
          responseBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .Response response = 3;</code>
       */
      public protocol.ResponseProtos.Response.Builder getResponseBuilder() {
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Response response = 3;</code>
       */
      public protocol.ResponseProtos.ResponseOrBuilder getResponseOrBuilder() {
        if ((typeCase_ == 3) && (responseBuilder_ != null)) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          if (typeCase_ == 3) {
            return (protocol.ResponseProtos.Response) type_;
          }
          return protocol.ResponseProtos.Response.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Response response = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          protocol.ResponseProtos.Response, protocol.ResponseProtos.Response.Builder, protocol.ResponseProtos.ResponseOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          if (!(typeCase_ == 3)) {
            type_ = protocol.ResponseProtos.Response.getDefaultInstance();
          }
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              protocol.ResponseProtos.Response, protocol.ResponseProtos.Response.Builder, protocol.ResponseProtos.ResponseOrBuilder>(
                  (protocol.ResponseProtos.Response) type_,
                  getParentForChildren(),
                  isClean());
          type_ = null;
        }
        typeCase_ = 3;
        return responseBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          protocol.EventProtos.Event, protocol.EventProtos.Event.Builder, protocol.EventProtos.EventOrBuilder> eventBuilder_;
      /**
       * <code>optional .Event event = 4;</code>
       */
      public boolean hasEvent() {
        return typeCase_ == 4;
      }
      /**
       * <code>optional .Event event = 4;</code>
       */
      public protocol.EventProtos.Event getEvent() {
        if (eventBuilder_ == null) {
          if (typeCase_ == 4) {
            return (protocol.EventProtos.Event) type_;
          }
          return protocol.EventProtos.Event.getDefaultInstance();
        } else {
          if (typeCase_ == 4) {
            return eventBuilder_.getMessage();
          }
          return protocol.EventProtos.Event.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Event event = 4;</code>
       */
      public Builder setEvent(protocol.EventProtos.Event value) {
        if (eventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          type_ = value;
          onChanged();
        } else {
          eventBuilder_.setMessage(value);
        }
        typeCase_ = 4;
        return this;
      }
      /**
       * <code>optional .Event event = 4;</code>
       */
      public Builder setEvent(
          protocol.EventProtos.Event.Builder builderForValue) {
        if (eventBuilder_ == null) {
          type_ = builderForValue.build();
          onChanged();
        } else {
          eventBuilder_.setMessage(builderForValue.build());
        }
        typeCase_ = 4;
        return this;
      }
      /**
       * <code>optional .Event event = 4;</code>
       */
      public Builder mergeEvent(protocol.EventProtos.Event value) {
        if (eventBuilder_ == null) {
          if (typeCase_ == 4 &&
              type_ != protocol.EventProtos.Event.getDefaultInstance()) {
            type_ = protocol.EventProtos.Event.newBuilder((protocol.EventProtos.Event) type_)
                .mergeFrom(value).buildPartial();
          } else {
            type_ = value;
          }
          onChanged();
        } else {
          if (typeCase_ == 4) {
            eventBuilder_.mergeFrom(value);
          }
          eventBuilder_.setMessage(value);
        }
        typeCase_ = 4;
        return this;
      }
      /**
       * <code>optional .Event event = 4;</code>
       */
      public Builder clearEvent() {
        if (eventBuilder_ == null) {
          if (typeCase_ == 4) {
            typeCase_ = 0;
            type_ = null;
            onChanged();
          }
        } else {
          if (typeCase_ == 4) {
            typeCase_ = 0;
            type_ = null;
          }
          eventBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .Event event = 4;</code>
       */
      public protocol.EventProtos.Event.Builder getEventBuilder() {
        return getEventFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Event event = 4;</code>
       */
      public protocol.EventProtos.EventOrBuilder getEventOrBuilder() {
        if ((typeCase_ == 4) && (eventBuilder_ != null)) {
          return eventBuilder_.getMessageOrBuilder();
        } else {
          if (typeCase_ == 4) {
            return (protocol.EventProtos.Event) type_;
          }
          return protocol.EventProtos.Event.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Event event = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          protocol.EventProtos.Event, protocol.EventProtos.Event.Builder, protocol.EventProtos.EventOrBuilder> 
          getEventFieldBuilder() {
        if (eventBuilder_ == null) {
          if (!(typeCase_ == 4)) {
            type_ = protocol.EventProtos.Event.getDefaultInstance();
          }
          eventBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              protocol.EventProtos.Event, protocol.EventProtos.Event.Builder, protocol.EventProtos.EventOrBuilder>(
                  (protocol.EventProtos.Event) type_,
                  getParentForChildren(),
                  isClean());
          type_ = null;
        }
        typeCase_ = 4;
        return eventBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Message)
    }

    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Message)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016messages.proto\032\016requests.proto\032\017respon" +
      "ses.proto\032\014events.proto\032\013enums.proto\"\212\001\n" +
      "\007Message\022\"\n\014playerColour\030\001 \002(\0162\014.ColourP" +
      "roto\022\033\n\007request\030\002 \001(\0132\010.RequestH\000\022\035\n\010res" +
      "ponse\030\003 \001(\0132\t.ResponseH\000\022\027\n\005event\030\004 \001(\0132" +
      "\006.EventH\000B\006\n\004typeB\031\n\010protocolB\rMessagePr" +
      "otos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protocol.RequestProtos.getDescriptor(),
          protocol.ResponseProtos.getDescriptor(),
          protocol.EventProtos.getDescriptor(),
          protocol.EnumProtos.getDescriptor(),
        }, assigner);
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "PlayerColour", "Request", "Response", "Event", "Type", });
    protocol.RequestProtos.getDescriptor();
    protocol.ResponseProtos.getDescriptor();
    protocol.EventProtos.getDescriptor();
    protocol.EnumProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
