// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources.proto

package protocol;

public final class ResourceProtos {
  private ResourceProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ResourceAllocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResourceAllocation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .ResourceCount resources = 1;</code>
     */
    boolean hasResources();
    /**
     * <code>required .ResourceCount resources = 1;</code>
     */
    protocol.ResourceProtos.ResourceCount getResources();
    /**
     * <code>required .ResourceCount resources = 1;</code>
     */
    protocol.ResourceProtos.ResourceCountOrBuilder getResourcesOrBuilder();

    /**
     * <code>required .ColourProto playerColour = 2;</code>
     */
    boolean hasPlayerColour();
    /**
     * <code>required .ColourProto playerColour = 2;</code>
     */
    protocol.EnumProtos.ColourProto getPlayerColour();
  }
  /**
   * Protobuf type {@code ResourceAllocation}
   */
  public static final class ResourceAllocation extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ResourceAllocation)
      ResourceAllocationOrBuilder {
    // Use ResourceAllocation.newBuilder() to construct.
    private ResourceAllocation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResourceAllocation(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResourceAllocation defaultInstance;
    public static ResourceAllocation getDefaultInstance() {
      return defaultInstance;
    }

    public ResourceAllocation getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResourceAllocation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              protocol.ResourceProtos.ResourceCount.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = resources_.toBuilder();
              }
              resources_ = input.readMessage(protocol.ResourceProtos.ResourceCount.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(resources_);
                resources_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              protocol.EnumProtos.ColourProto value = protocol.EnumProtos.ColourProto.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                playerColour_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.ResourceProtos.internal_static_ResourceAllocation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.ResourceProtos.internal_static_ResourceAllocation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.ResourceProtos.ResourceAllocation.class, protocol.ResourceProtos.ResourceAllocation.Builder.class);
    }

    public static com.google.protobuf.Parser<ResourceAllocation> PARSER =
        new com.google.protobuf.AbstractParser<ResourceAllocation>() {
      public ResourceAllocation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResourceAllocation(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResourceAllocation> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RESOURCES_FIELD_NUMBER = 1;
    private protocol.ResourceProtos.ResourceCount resources_;
    /**
     * <code>required .ResourceCount resources = 1;</code>
     */
    public boolean hasResources() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .ResourceCount resources = 1;</code>
     */
    public protocol.ResourceProtos.ResourceCount getResources() {
      return resources_;
    }
    /**
     * <code>required .ResourceCount resources = 1;</code>
     */
    public protocol.ResourceProtos.ResourceCountOrBuilder getResourcesOrBuilder() {
      return resources_;
    }

    public static final int PLAYERCOLOUR_FIELD_NUMBER = 2;
    private protocol.EnumProtos.ColourProto playerColour_;
    /**
     * <code>required .ColourProto playerColour = 2;</code>
     */
    public boolean hasPlayerColour() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .ColourProto playerColour = 2;</code>
     */
    public protocol.EnumProtos.ColourProto getPlayerColour() {
      return playerColour_;
    }

    private void initFields() {
      resources_ = protocol.ResourceProtos.ResourceCount.getDefaultInstance();
      playerColour_ = protocol.EnumProtos.ColourProto.RED;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasResources()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPlayerColour()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getResources().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, resources_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, playerColour_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, resources_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, playerColour_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protocol.ResourceProtos.ResourceAllocation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ResourceProtos.ResourceAllocation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ResourceProtos.ResourceAllocation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ResourceProtos.ResourceAllocation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ResourceProtos.ResourceAllocation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.ResourceProtos.ResourceAllocation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol.ResourceProtos.ResourceAllocation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol.ResourceProtos.ResourceAllocation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol.ResourceProtos.ResourceAllocation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.ResourceProtos.ResourceAllocation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocol.ResourceProtos.ResourceAllocation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResourceAllocation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResourceAllocation)
        protocol.ResourceProtos.ResourceAllocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.ResourceProtos.internal_static_ResourceAllocation_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.ResourceProtos.internal_static_ResourceAllocation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.ResourceProtos.ResourceAllocation.class, protocol.ResourceProtos.ResourceAllocation.Builder.class);
      }

      // Construct using protocol.ResourceProtos.ResourceAllocation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getResourcesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (resourcesBuilder_ == null) {
          resources_ = protocol.ResourceProtos.ResourceCount.getDefaultInstance();
        } else {
          resourcesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        playerColour_ = protocol.EnumProtos.ColourProto.RED;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.ResourceProtos.internal_static_ResourceAllocation_descriptor;
      }

      public protocol.ResourceProtos.ResourceAllocation getDefaultInstanceForType() {
        return protocol.ResourceProtos.ResourceAllocation.getDefaultInstance();
      }

      public protocol.ResourceProtos.ResourceAllocation build() {
        protocol.ResourceProtos.ResourceAllocation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.ResourceProtos.ResourceAllocation buildPartial() {
        protocol.ResourceProtos.ResourceAllocation result = new protocol.ResourceProtos.ResourceAllocation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (resourcesBuilder_ == null) {
          result.resources_ = resources_;
        } else {
          result.resources_ = resourcesBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.playerColour_ = playerColour_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.ResourceProtos.ResourceAllocation) {
          return mergeFrom((protocol.ResourceProtos.ResourceAllocation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.ResourceProtos.ResourceAllocation other) {
        if (other == protocol.ResourceProtos.ResourceAllocation.getDefaultInstance()) return this;
        if (other.hasResources()) {
          mergeResources(other.getResources());
        }
        if (other.hasPlayerColour()) {
          setPlayerColour(other.getPlayerColour());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResources()) {
          
          return false;
        }
        if (!hasPlayerColour()) {
          
          return false;
        }
        if (!getResources().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.ResourceProtos.ResourceAllocation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.ResourceProtos.ResourceAllocation) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private protocol.ResourceProtos.ResourceCount resources_ = protocol.ResourceProtos.ResourceCount.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          protocol.ResourceProtos.ResourceCount, protocol.ResourceProtos.ResourceCount.Builder, protocol.ResourceProtos.ResourceCountOrBuilder> resourcesBuilder_;
      /**
       * <code>required .ResourceCount resources = 1;</code>
       */
      public boolean hasResources() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .ResourceCount resources = 1;</code>
       */
      public protocol.ResourceProtos.ResourceCount getResources() {
        if (resourcesBuilder_ == null) {
          return resources_;
        } else {
          return resourcesBuilder_.getMessage();
        }
      }
      /**
       * <code>required .ResourceCount resources = 1;</code>
       */
      public Builder setResources(protocol.ResourceProtos.ResourceCount value) {
        if (resourcesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          resources_ = value;
          onChanged();
        } else {
          resourcesBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .ResourceCount resources = 1;</code>
       */
      public Builder setResources(
          protocol.ResourceProtos.ResourceCount.Builder builderForValue) {
        if (resourcesBuilder_ == null) {
          resources_ = builderForValue.build();
          onChanged();
        } else {
          resourcesBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .ResourceCount resources = 1;</code>
       */
      public Builder mergeResources(protocol.ResourceProtos.ResourceCount value) {
        if (resourcesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              resources_ != protocol.ResourceProtos.ResourceCount.getDefaultInstance()) {
            resources_ =
              protocol.ResourceProtos.ResourceCount.newBuilder(resources_).mergeFrom(value).buildPartial();
          } else {
            resources_ = value;
          }
          onChanged();
        } else {
          resourcesBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .ResourceCount resources = 1;</code>
       */
      public Builder clearResources() {
        if (resourcesBuilder_ == null) {
          resources_ = protocol.ResourceProtos.ResourceCount.getDefaultInstance();
          onChanged();
        } else {
          resourcesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .ResourceCount resources = 1;</code>
       */
      public protocol.ResourceProtos.ResourceCount.Builder getResourcesBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getResourcesFieldBuilder().getBuilder();
      }
      /**
       * <code>required .ResourceCount resources = 1;</code>
       */
      public protocol.ResourceProtos.ResourceCountOrBuilder getResourcesOrBuilder() {
        if (resourcesBuilder_ != null) {
          return resourcesBuilder_.getMessageOrBuilder();
        } else {
          return resources_;
        }
      }
      /**
       * <code>required .ResourceCount resources = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          protocol.ResourceProtos.ResourceCount, protocol.ResourceProtos.ResourceCount.Builder, protocol.ResourceProtos.ResourceCountOrBuilder> 
          getResourcesFieldBuilder() {
        if (resourcesBuilder_ == null) {
          resourcesBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              protocol.ResourceProtos.ResourceCount, protocol.ResourceProtos.ResourceCount.Builder, protocol.ResourceProtos.ResourceCountOrBuilder>(
                  getResources(),
                  getParentForChildren(),
                  isClean());
          resources_ = null;
        }
        return resourcesBuilder_;
      }

      private protocol.EnumProtos.ColourProto playerColour_ = protocol.EnumProtos.ColourProto.RED;
      /**
       * <code>required .ColourProto playerColour = 2;</code>
       */
      public boolean hasPlayerColour() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .ColourProto playerColour = 2;</code>
       */
      public protocol.EnumProtos.ColourProto getPlayerColour() {
        return playerColour_;
      }
      /**
       * <code>required .ColourProto playerColour = 2;</code>
       */
      public Builder setPlayerColour(protocol.EnumProtos.ColourProto value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        playerColour_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .ColourProto playerColour = 2;</code>
       */
      public Builder clearPlayerColour() {
        bitField0_ = (bitField0_ & ~0x00000002);
        playerColour_ = protocol.EnumProtos.ColourProto.RED;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ResourceAllocation)
    }

    static {
      defaultInstance = new ResourceAllocation(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ResourceAllocation)
  }

  public interface ResourceCountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResourceCount)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 brick = 1;</code>
     */
    boolean hasBrick();
    /**
     * <code>required int32 brick = 1;</code>
     */
    int getBrick();

    /**
     * <code>required int32 lumber = 2;</code>
     */
    boolean hasLumber();
    /**
     * <code>required int32 lumber = 2;</code>
     */
    int getLumber();

    /**
     * <code>required int32 wool = 3;</code>
     */
    boolean hasWool();
    /**
     * <code>required int32 wool = 3;</code>
     */
    int getWool();

    /**
     * <code>required int32 grain = 4;</code>
     */
    boolean hasGrain();
    /**
     * <code>required int32 grain = 4;</code>
     */
    int getGrain();

    /**
     * <code>required int32 ore = 5;</code>
     */
    boolean hasOre();
    /**
     * <code>required int32 ore = 5;</code>
     */
    int getOre();
  }
  /**
   * Protobuf type {@code ResourceCount}
   */
  public static final class ResourceCount extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ResourceCount)
      ResourceCountOrBuilder {
    // Use ResourceCount.newBuilder() to construct.
    private ResourceCount(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResourceCount(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResourceCount defaultInstance;
    public static ResourceCount getDefaultInstance() {
      return defaultInstance;
    }

    public ResourceCount getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResourceCount(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              brick_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              lumber_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              wool_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              grain_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              ore_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.ResourceProtos.internal_static_ResourceCount_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.ResourceProtos.internal_static_ResourceCount_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.ResourceProtos.ResourceCount.class, protocol.ResourceProtos.ResourceCount.Builder.class);
    }

    public static com.google.protobuf.Parser<ResourceCount> PARSER =
        new com.google.protobuf.AbstractParser<ResourceCount>() {
      public ResourceCount parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResourceCount(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResourceCount> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int BRICK_FIELD_NUMBER = 1;
    private int brick_;
    /**
     * <code>required int32 brick = 1;</code>
     */
    public boolean hasBrick() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 brick = 1;</code>
     */
    public int getBrick() {
      return brick_;
    }

    public static final int LUMBER_FIELD_NUMBER = 2;
    private int lumber_;
    /**
     * <code>required int32 lumber = 2;</code>
     */
    public boolean hasLumber() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 lumber = 2;</code>
     */
    public int getLumber() {
      return lumber_;
    }

    public static final int WOOL_FIELD_NUMBER = 3;
    private int wool_;
    /**
     * <code>required int32 wool = 3;</code>
     */
    public boolean hasWool() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 wool = 3;</code>
     */
    public int getWool() {
      return wool_;
    }

    public static final int GRAIN_FIELD_NUMBER = 4;
    private int grain_;
    /**
     * <code>required int32 grain = 4;</code>
     */
    public boolean hasGrain() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 grain = 4;</code>
     */
    public int getGrain() {
      return grain_;
    }

    public static final int ORE_FIELD_NUMBER = 5;
    private int ore_;
    /**
     * <code>required int32 ore = 5;</code>
     */
    public boolean hasOre() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 ore = 5;</code>
     */
    public int getOre() {
      return ore_;
    }

    private void initFields() {
      brick_ = 0;
      lumber_ = 0;
      wool_ = 0;
      grain_ = 0;
      ore_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasBrick()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWool()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGrain()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOre()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, brick_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, lumber_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, wool_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, grain_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, ore_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, brick_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, lumber_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, wool_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, grain_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, ore_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protocol.ResourceProtos.ResourceCount parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ResourceProtos.ResourceCount parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ResourceProtos.ResourceCount parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ResourceProtos.ResourceCount parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ResourceProtos.ResourceCount parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.ResourceProtos.ResourceCount parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol.ResourceProtos.ResourceCount parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol.ResourceProtos.ResourceCount parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol.ResourceProtos.ResourceCount parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.ResourceProtos.ResourceCount parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocol.ResourceProtos.ResourceCount prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResourceCount}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResourceCount)
        protocol.ResourceProtos.ResourceCountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.ResourceProtos.internal_static_ResourceCount_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.ResourceProtos.internal_static_ResourceCount_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.ResourceProtos.ResourceCount.class, protocol.ResourceProtos.ResourceCount.Builder.class);
      }

      // Construct using protocol.ResourceProtos.ResourceCount.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        brick_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        lumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        wool_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        grain_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        ore_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.ResourceProtos.internal_static_ResourceCount_descriptor;
      }

      public protocol.ResourceProtos.ResourceCount getDefaultInstanceForType() {
        return protocol.ResourceProtos.ResourceCount.getDefaultInstance();
      }

      public protocol.ResourceProtos.ResourceCount build() {
        protocol.ResourceProtos.ResourceCount result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.ResourceProtos.ResourceCount buildPartial() {
        protocol.ResourceProtos.ResourceCount result = new protocol.ResourceProtos.ResourceCount(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.brick_ = brick_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.lumber_ = lumber_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.wool_ = wool_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.grain_ = grain_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.ore_ = ore_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.ResourceProtos.ResourceCount) {
          return mergeFrom((protocol.ResourceProtos.ResourceCount)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.ResourceProtos.ResourceCount other) {
        if (other == protocol.ResourceProtos.ResourceCount.getDefaultInstance()) return this;
        if (other.hasBrick()) {
          setBrick(other.getBrick());
        }
        if (other.hasLumber()) {
          setLumber(other.getLumber());
        }
        if (other.hasWool()) {
          setWool(other.getWool());
        }
        if (other.hasGrain()) {
          setGrain(other.getGrain());
        }
        if (other.hasOre()) {
          setOre(other.getOre());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBrick()) {
          
          return false;
        }
        if (!hasLumber()) {
          
          return false;
        }
        if (!hasWool()) {
          
          return false;
        }
        if (!hasGrain()) {
          
          return false;
        }
        if (!hasOre()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.ResourceProtos.ResourceCount parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.ResourceProtos.ResourceCount) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int brick_ ;
      /**
       * <code>required int32 brick = 1;</code>
       */
      public boolean hasBrick() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 brick = 1;</code>
       */
      public int getBrick() {
        return brick_;
      }
      /**
       * <code>required int32 brick = 1;</code>
       */
      public Builder setBrick(int value) {
        bitField0_ |= 0x00000001;
        brick_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 brick = 1;</code>
       */
      public Builder clearBrick() {
        bitField0_ = (bitField0_ & ~0x00000001);
        brick_ = 0;
        onChanged();
        return this;
      }

      private int lumber_ ;
      /**
       * <code>required int32 lumber = 2;</code>
       */
      public boolean hasLumber() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 lumber = 2;</code>
       */
      public int getLumber() {
        return lumber_;
      }
      /**
       * <code>required int32 lumber = 2;</code>
       */
      public Builder setLumber(int value) {
        bitField0_ |= 0x00000002;
        lumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 lumber = 2;</code>
       */
      public Builder clearLumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lumber_ = 0;
        onChanged();
        return this;
      }

      private int wool_ ;
      /**
       * <code>required int32 wool = 3;</code>
       */
      public boolean hasWool() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 wool = 3;</code>
       */
      public int getWool() {
        return wool_;
      }
      /**
       * <code>required int32 wool = 3;</code>
       */
      public Builder setWool(int value) {
        bitField0_ |= 0x00000004;
        wool_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 wool = 3;</code>
       */
      public Builder clearWool() {
        bitField0_ = (bitField0_ & ~0x00000004);
        wool_ = 0;
        onChanged();
        return this;
      }

      private int grain_ ;
      /**
       * <code>required int32 grain = 4;</code>
       */
      public boolean hasGrain() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 grain = 4;</code>
       */
      public int getGrain() {
        return grain_;
      }
      /**
       * <code>required int32 grain = 4;</code>
       */
      public Builder setGrain(int value) {
        bitField0_ |= 0x00000008;
        grain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 grain = 4;</code>
       */
      public Builder clearGrain() {
        bitField0_ = (bitField0_ & ~0x00000008);
        grain_ = 0;
        onChanged();
        return this;
      }

      private int ore_ ;
      /**
       * <code>required int32 ore = 5;</code>
       */
      public boolean hasOre() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 ore = 5;</code>
       */
      public int getOre() {
        return ore_;
      }
      /**
       * <code>required int32 ore = 5;</code>
       */
      public Builder setOre(int value) {
        bitField0_ |= 0x00000010;
        ore_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 ore = 5;</code>
       */
      public Builder clearOre() {
        bitField0_ = (bitField0_ & ~0x00000010);
        ore_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ResourceCount)
    }

    static {
      defaultInstance = new ResourceCount(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ResourceCount)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResourceAllocation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ResourceAllocation_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResourceCount_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ResourceCount_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017resources.proto\032\013enums.proto\"[\n\022Resour" +
      "ceAllocation\022!\n\tresources\030\001 \002(\0132\016.Resour" +
      "ceCount\022\"\n\014playerColour\030\002 \002(\0162\014.ColourPr" +
      "oto\"X\n\rResourceCount\022\r\n\005brick\030\001 \002(\005\022\016\n\006l" +
      "umber\030\002 \002(\005\022\014\n\004wool\030\003 \002(\005\022\r\n\005grain\030\004 \002(\005" +
      "\022\013\n\003ore\030\005 \002(\005B\032\n\010protocolB\016ResourceProto" +
      "s"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protocol.EnumProtos.getDescriptor(),
        }, assigner);
    internal_static_ResourceAllocation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ResourceAllocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ResourceAllocation_descriptor,
        new java.lang.String[] { "Resources", "PlayerColour", });
    internal_static_ResourceCount_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ResourceCount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ResourceCount_descriptor,
        new java.lang.String[] { "Brick", "Lumber", "Wool", "Grain", "Ore", });
    protocol.EnumProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
