package enums;

public enum Move
{
	BUILD_ROAD,
	BUILD_SETTLEMENT,
	UPGRADE_SETTLEMENT,
	BUY_CARD,
	SPEND_CARD,
	MOVE_ROBBER,
	CLOSE, PLAY_ROADBUILDINGCARD, PLAY_MONOPOLYCARD, PLAY_YEAROFPLENTYCARD, PLAY_ROADLIBRARYCARD, PLAY_UNIVERSITYCARD, PLAY_KNIGHTCARD, TRADE_REQUEST ;
}
