// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trade/trade.proto

package trade;

public final class Trade {
  private Trade() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code trade.Response}
   */
  public enum Response
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>REJECT = 0;</code>
     */
    REJECT(0),
    /**
     * <code>ACCEPT = 1;</code>
     */
    ACCEPT(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>REJECT = 0;</code>
     */
    public static final int REJECT_VALUE = 0;
    /**
     * <code>ACCEPT = 1;</code>
     */
    public static final int ACCEPT_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Response valueOf(int value) {
      return forNumber(value);
    }

    public static Response forNumber(int value) {
      switch (value) {
        case 0: return REJECT;
        case 1: return ACCEPT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Response>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Response> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Response>() {
            public Response findValueByNumber(int number) {
              return Response.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return trade.Trade.getDescriptor().getEnumTypes().get(0);
    }

    private static final Response[] VALUES = values();

    public static Response valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Response(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:trade.Response)
  }

  public interface KindOrBuilder extends
      // @@protoc_insertion_point(interface_extends:trade.Kind)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.trade.WithPlayer player = 1;</code>
     */
    trade.Trade.WithPlayer getPlayer();
    /**
     * <code>.trade.WithPlayer player = 1;</code>
     */
    trade.Trade.WithPlayerOrBuilder getPlayerOrBuilder();

    /**
     * <code>.trade.WithBank bank = 2;</code>
     */
    trade.Trade.WithBank getBank();
    /**
     * <code>.trade.WithBank bank = 2;</code>
     */
    trade.Trade.WithBankOrBuilder getBankOrBuilder();

    public trade.Trade.Kind.TradeCase getTradeCase();
  }
  /**
   * Protobuf type {@code trade.Kind}
   */
  public  static final class Kind extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:trade.Kind)
      KindOrBuilder {
    // Use Kind.newBuilder() to construct.
    private Kind(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Kind() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Kind(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              trade.Trade.WithPlayer.Builder subBuilder = null;
              if (tradeCase_ == 1) {
                subBuilder = ((trade.Trade.WithPlayer) trade_).toBuilder();
              }
              trade_ =
                  input.readMessage(trade.Trade.WithPlayer.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((trade.Trade.WithPlayer) trade_);
                trade_ = subBuilder.buildPartial();
              }
              tradeCase_ = 1;
              break;
            }
            case 18: {
              trade.Trade.WithBank.Builder subBuilder = null;
              if (tradeCase_ == 2) {
                subBuilder = ((trade.Trade.WithBank) trade_).toBuilder();
              }
              trade_ =
                  input.readMessage(trade.Trade.WithBank.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((trade.Trade.WithBank) trade_);
                trade_ = subBuilder.buildPartial();
              }
              tradeCase_ = 2;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return trade.Trade.internal_static_trade_Kind_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return trade.Trade.internal_static_trade_Kind_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              trade.Trade.Kind.class, trade.Trade.Kind.Builder.class);
    }

    private int tradeCase_ = 0;
    private java.lang.Object trade_;
    public enum TradeCase
        implements com.google.protobuf.Internal.EnumLite {
      PLAYER(1),
      BANK(2),
      TRADE_NOT_SET(0);
      private final int value;
      private TradeCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static TradeCase valueOf(int value) {
        return forNumber(value);
      }

      public static TradeCase forNumber(int value) {
        switch (value) {
          case 1: return PLAYER;
          case 2: return BANK;
          case 0: return TRADE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public TradeCase
    getTradeCase() {
      return TradeCase.forNumber(
          tradeCase_);
    }

    public static final int PLAYER_FIELD_NUMBER = 1;
    /**
     * <code>.trade.WithPlayer player = 1;</code>
     */
    public trade.Trade.WithPlayer getPlayer() {
      if (tradeCase_ == 1) {
         return (trade.Trade.WithPlayer) trade_;
      }
      return trade.Trade.WithPlayer.getDefaultInstance();
    }
    /**
     * <code>.trade.WithPlayer player = 1;</code>
     */
    public trade.Trade.WithPlayerOrBuilder getPlayerOrBuilder() {
      if (tradeCase_ == 1) {
         return (trade.Trade.WithPlayer) trade_;
      }
      return trade.Trade.WithPlayer.getDefaultInstance();
    }

    public static final int BANK_FIELD_NUMBER = 2;
    /**
     * <code>.trade.WithBank bank = 2;</code>
     */
    public trade.Trade.WithBank getBank() {
      if (tradeCase_ == 2) {
         return (trade.Trade.WithBank) trade_;
      }
      return trade.Trade.WithBank.getDefaultInstance();
    }
    /**
     * <code>.trade.WithBank bank = 2;</code>
     */
    public trade.Trade.WithBankOrBuilder getBankOrBuilder() {
      if (tradeCase_ == 2) {
         return (trade.Trade.WithBank) trade_;
      }
      return trade.Trade.WithBank.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (tradeCase_ == 1) {
        output.writeMessage(1, (trade.Trade.WithPlayer) trade_);
      }
      if (tradeCase_ == 2) {
        output.writeMessage(2, (trade.Trade.WithBank) trade_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (tradeCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (trade.Trade.WithPlayer) trade_);
      }
      if (tradeCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (trade.Trade.WithBank) trade_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof trade.Trade.Kind)) {
        return super.equals(obj);
      }
      trade.Trade.Kind other = (trade.Trade.Kind) obj;

      boolean result = true;
      result = result && getTradeCase().equals(
          other.getTradeCase());
      if (!result) return false;
      switch (tradeCase_) {
        case 1:
          result = result && getPlayer()
              .equals(other.getPlayer());
          break;
        case 2:
          result = result && getBank()
              .equals(other.getBank());
          break;
        case 0:
        default:
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (tradeCase_) {
        case 1:
          hash = (37 * hash) + PLAYER_FIELD_NUMBER;
          hash = (53 * hash) + getPlayer().hashCode();
          break;
        case 2:
          hash = (37 * hash) + BANK_FIELD_NUMBER;
          hash = (53 * hash) + getBank().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static trade.Trade.Kind parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static trade.Trade.Kind parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static trade.Trade.Kind parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static trade.Trade.Kind parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static trade.Trade.Kind parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static trade.Trade.Kind parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static trade.Trade.Kind parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static trade.Trade.Kind parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static trade.Trade.Kind parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static trade.Trade.Kind parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(trade.Trade.Kind prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code trade.Kind}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:trade.Kind)
        trade.Trade.KindOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return trade.Trade.internal_static_trade_Kind_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return trade.Trade.internal_static_trade_Kind_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                trade.Trade.Kind.class, trade.Trade.Kind.Builder.class);
      }

      // Construct using trade.Trade.Kind.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        tradeCase_ = 0;
        trade_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return trade.Trade.internal_static_trade_Kind_descriptor;
      }

      public trade.Trade.Kind getDefaultInstanceForType() {
        return trade.Trade.Kind.getDefaultInstance();
      }

      public trade.Trade.Kind build() {
        trade.Trade.Kind result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public trade.Trade.Kind buildPartial() {
        trade.Trade.Kind result = new trade.Trade.Kind(this);
        if (tradeCase_ == 1) {
          if (playerBuilder_ == null) {
            result.trade_ = trade_;
          } else {
            result.trade_ = playerBuilder_.build();
          }
        }
        if (tradeCase_ == 2) {
          if (bankBuilder_ == null) {
            result.trade_ = trade_;
          } else {
            result.trade_ = bankBuilder_.build();
          }
        }
        result.tradeCase_ = tradeCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof trade.Trade.Kind) {
          return mergeFrom((trade.Trade.Kind)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(trade.Trade.Kind other) {
        if (other == trade.Trade.Kind.getDefaultInstance()) return this;
        switch (other.getTradeCase()) {
          case PLAYER: {
            mergePlayer(other.getPlayer());
            break;
          }
          case BANK: {
            mergeBank(other.getBank());
            break;
          }
          case TRADE_NOT_SET: {
            break;
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        trade.Trade.Kind parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (trade.Trade.Kind) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int tradeCase_ = 0;
      private java.lang.Object trade_;
      public TradeCase
          getTradeCase() {
        return TradeCase.forNumber(
            tradeCase_);
      }

      public Builder clearTrade() {
        tradeCase_ = 0;
        trade_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          trade.Trade.WithPlayer, trade.Trade.WithPlayer.Builder, trade.Trade.WithPlayerOrBuilder> playerBuilder_;
      /**
       * <code>.trade.WithPlayer player = 1;</code>
       */
      public trade.Trade.WithPlayer getPlayer() {
        if (playerBuilder_ == null) {
          if (tradeCase_ == 1) {
            return (trade.Trade.WithPlayer) trade_;
          }
          return trade.Trade.WithPlayer.getDefaultInstance();
        } else {
          if (tradeCase_ == 1) {
            return playerBuilder_.getMessage();
          }
          return trade.Trade.WithPlayer.getDefaultInstance();
        }
      }
      /**
       * <code>.trade.WithPlayer player = 1;</code>
       */
      public Builder setPlayer(trade.Trade.WithPlayer value) {
        if (playerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          trade_ = value;
          onChanged();
        } else {
          playerBuilder_.setMessage(value);
        }
        tradeCase_ = 1;
        return this;
      }
      /**
       * <code>.trade.WithPlayer player = 1;</code>
       */
      public Builder setPlayer(
          trade.Trade.WithPlayer.Builder builderForValue) {
        if (playerBuilder_ == null) {
          trade_ = builderForValue.build();
          onChanged();
        } else {
          playerBuilder_.setMessage(builderForValue.build());
        }
        tradeCase_ = 1;
        return this;
      }
      /**
       * <code>.trade.WithPlayer player = 1;</code>
       */
      public Builder mergePlayer(trade.Trade.WithPlayer value) {
        if (playerBuilder_ == null) {
          if (tradeCase_ == 1 &&
              trade_ != trade.Trade.WithPlayer.getDefaultInstance()) {
            trade_ = trade.Trade.WithPlayer.newBuilder((trade.Trade.WithPlayer) trade_)
                .mergeFrom(value).buildPartial();
          } else {
            trade_ = value;
          }
          onChanged();
        } else {
          if (tradeCase_ == 1) {
            playerBuilder_.mergeFrom(value);
          }
          playerBuilder_.setMessage(value);
        }
        tradeCase_ = 1;
        return this;
      }
      /**
       * <code>.trade.WithPlayer player = 1;</code>
       */
      public Builder clearPlayer() {
        if (playerBuilder_ == null) {
          if (tradeCase_ == 1) {
            tradeCase_ = 0;
            trade_ = null;
            onChanged();
          }
        } else {
          if (tradeCase_ == 1) {
            tradeCase_ = 0;
            trade_ = null;
          }
          playerBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.trade.WithPlayer player = 1;</code>
       */
      public trade.Trade.WithPlayer.Builder getPlayerBuilder() {
        return getPlayerFieldBuilder().getBuilder();
      }
      /**
       * <code>.trade.WithPlayer player = 1;</code>
       */
      public trade.Trade.WithPlayerOrBuilder getPlayerOrBuilder() {
        if ((tradeCase_ == 1) && (playerBuilder_ != null)) {
          return playerBuilder_.getMessageOrBuilder();
        } else {
          if (tradeCase_ == 1) {
            return (trade.Trade.WithPlayer) trade_;
          }
          return trade.Trade.WithPlayer.getDefaultInstance();
        }
      }
      /**
       * <code>.trade.WithPlayer player = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          trade.Trade.WithPlayer, trade.Trade.WithPlayer.Builder, trade.Trade.WithPlayerOrBuilder> 
          getPlayerFieldBuilder() {
        if (playerBuilder_ == null) {
          if (!(tradeCase_ == 1)) {
            trade_ = trade.Trade.WithPlayer.getDefaultInstance();
          }
          playerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              trade.Trade.WithPlayer, trade.Trade.WithPlayer.Builder, trade.Trade.WithPlayerOrBuilder>(
                  (trade.Trade.WithPlayer) trade_,
                  getParentForChildren(),
                  isClean());
          trade_ = null;
        }
        tradeCase_ = 1;
        onChanged();;
        return playerBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          trade.Trade.WithBank, trade.Trade.WithBank.Builder, trade.Trade.WithBankOrBuilder> bankBuilder_;
      /**
       * <code>.trade.WithBank bank = 2;</code>
       */
      public trade.Trade.WithBank getBank() {
        if (bankBuilder_ == null) {
          if (tradeCase_ == 2) {
            return (trade.Trade.WithBank) trade_;
          }
          return trade.Trade.WithBank.getDefaultInstance();
        } else {
          if (tradeCase_ == 2) {
            return bankBuilder_.getMessage();
          }
          return trade.Trade.WithBank.getDefaultInstance();
        }
      }
      /**
       * <code>.trade.WithBank bank = 2;</code>
       */
      public Builder setBank(trade.Trade.WithBank value) {
        if (bankBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          trade_ = value;
          onChanged();
        } else {
          bankBuilder_.setMessage(value);
        }
        tradeCase_ = 2;
        return this;
      }
      /**
       * <code>.trade.WithBank bank = 2;</code>
       */
      public Builder setBank(
          trade.Trade.WithBank.Builder builderForValue) {
        if (bankBuilder_ == null) {
          trade_ = builderForValue.build();
          onChanged();
        } else {
          bankBuilder_.setMessage(builderForValue.build());
        }
        tradeCase_ = 2;
        return this;
      }
      /**
       * <code>.trade.WithBank bank = 2;</code>
       */
      public Builder mergeBank(trade.Trade.WithBank value) {
        if (bankBuilder_ == null) {
          if (tradeCase_ == 2 &&
              trade_ != trade.Trade.WithBank.getDefaultInstance()) {
            trade_ = trade.Trade.WithBank.newBuilder((trade.Trade.WithBank) trade_)
                .mergeFrom(value).buildPartial();
          } else {
            trade_ = value;
          }
          onChanged();
        } else {
          if (tradeCase_ == 2) {
            bankBuilder_.mergeFrom(value);
          }
          bankBuilder_.setMessage(value);
        }
        tradeCase_ = 2;
        return this;
      }
      /**
       * <code>.trade.WithBank bank = 2;</code>
       */
      public Builder clearBank() {
        if (bankBuilder_ == null) {
          if (tradeCase_ == 2) {
            tradeCase_ = 0;
            trade_ = null;
            onChanged();
          }
        } else {
          if (tradeCase_ == 2) {
            tradeCase_ = 0;
            trade_ = null;
          }
          bankBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.trade.WithBank bank = 2;</code>
       */
      public trade.Trade.WithBank.Builder getBankBuilder() {
        return getBankFieldBuilder().getBuilder();
      }
      /**
       * <code>.trade.WithBank bank = 2;</code>
       */
      public trade.Trade.WithBankOrBuilder getBankOrBuilder() {
        if ((tradeCase_ == 2) && (bankBuilder_ != null)) {
          return bankBuilder_.getMessageOrBuilder();
        } else {
          if (tradeCase_ == 2) {
            return (trade.Trade.WithBank) trade_;
          }
          return trade.Trade.WithBank.getDefaultInstance();
        }
      }
      /**
       * <code>.trade.WithBank bank = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          trade.Trade.WithBank, trade.Trade.WithBank.Builder, trade.Trade.WithBankOrBuilder> 
          getBankFieldBuilder() {
        if (bankBuilder_ == null) {
          if (!(tradeCase_ == 2)) {
            trade_ = trade.Trade.WithBank.getDefaultInstance();
          }
          bankBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              trade.Trade.WithBank, trade.Trade.WithBank.Builder, trade.Trade.WithBankOrBuilder>(
                  (trade.Trade.WithBank) trade_,
                  getParentForChildren(),
                  isClean());
          trade_ = null;
        }
        tradeCase_ = 2;
        onChanged();;
        return bankBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:trade.Kind)
    }

    // @@protoc_insertion_point(class_scope:trade.Kind)
    private static final trade.Trade.Kind DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new trade.Trade.Kind();
    }

    public static trade.Trade.Kind getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Kind>
        PARSER = new com.google.protobuf.AbstractParser<Kind>() {
      public Kind parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Kind(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Kind> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Kind> getParserForType() {
      return PARSER;
    }

    public trade.Trade.Kind getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WithBankOrBuilder extends
      // @@protoc_insertion_point(interface_extends:trade.WithBank)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.resource.Counts offering = 1;</code>
     */
    boolean hasOffering();
    /**
     * <code>.resource.Counts offering = 1;</code>
     */
    resource.Resource.Counts getOffering();
    /**
     * <code>.resource.Counts offering = 1;</code>
     */
    resource.Resource.CountsOrBuilder getOfferingOrBuilder();

    /**
     * <code>.resource.Counts wanting = 2;</code>
     */
    boolean hasWanting();
    /**
     * <code>.resource.Counts wanting = 2;</code>
     */
    resource.Resource.Counts getWanting();
    /**
     * <code>.resource.Counts wanting = 2;</code>
     */
    resource.Resource.CountsOrBuilder getWantingOrBuilder();
  }
  /**
   * Protobuf type {@code trade.WithBank}
   */
  public  static final class WithBank extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:trade.WithBank)
      WithBankOrBuilder {
    // Use WithBank.newBuilder() to construct.
    private WithBank(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WithBank() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private WithBank(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              resource.Resource.Counts.Builder subBuilder = null;
              if (offering_ != null) {
                subBuilder = offering_.toBuilder();
              }
              offering_ = input.readMessage(resource.Resource.Counts.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(offering_);
                offering_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              resource.Resource.Counts.Builder subBuilder = null;
              if (wanting_ != null) {
                subBuilder = wanting_.toBuilder();
              }
              wanting_ = input.readMessage(resource.Resource.Counts.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(wanting_);
                wanting_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return trade.Trade.internal_static_trade_WithBank_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return trade.Trade.internal_static_trade_WithBank_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              trade.Trade.WithBank.class, trade.Trade.WithBank.Builder.class);
    }

    public static final int OFFERING_FIELD_NUMBER = 1;
    private resource.Resource.Counts offering_;
    /**
     * <code>.resource.Counts offering = 1;</code>
     */
    public boolean hasOffering() {
      return offering_ != null;
    }
    /**
     * <code>.resource.Counts offering = 1;</code>
     */
    public resource.Resource.Counts getOffering() {
      return offering_ == null ? resource.Resource.Counts.getDefaultInstance() : offering_;
    }
    /**
     * <code>.resource.Counts offering = 1;</code>
     */
    public resource.Resource.CountsOrBuilder getOfferingOrBuilder() {
      return getOffering();
    }

    public static final int WANTING_FIELD_NUMBER = 2;
    private resource.Resource.Counts wanting_;
    /**
     * <code>.resource.Counts wanting = 2;</code>
     */
    public boolean hasWanting() {
      return wanting_ != null;
    }
    /**
     * <code>.resource.Counts wanting = 2;</code>
     */
    public resource.Resource.Counts getWanting() {
      return wanting_ == null ? resource.Resource.Counts.getDefaultInstance() : wanting_;
    }
    /**
     * <code>.resource.Counts wanting = 2;</code>
     */
    public resource.Resource.CountsOrBuilder getWantingOrBuilder() {
      return getWanting();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (offering_ != null) {
        output.writeMessage(1, getOffering());
      }
      if (wanting_ != null) {
        output.writeMessage(2, getWanting());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (offering_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getOffering());
      }
      if (wanting_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getWanting());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof trade.Trade.WithBank)) {
        return super.equals(obj);
      }
      trade.Trade.WithBank other = (trade.Trade.WithBank) obj;

      boolean result = true;
      result = result && (hasOffering() == other.hasOffering());
      if (hasOffering()) {
        result = result && getOffering()
            .equals(other.getOffering());
      }
      result = result && (hasWanting() == other.hasWanting());
      if (hasWanting()) {
        result = result && getWanting()
            .equals(other.getWanting());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasOffering()) {
        hash = (37 * hash) + OFFERING_FIELD_NUMBER;
        hash = (53 * hash) + getOffering().hashCode();
      }
      if (hasWanting()) {
        hash = (37 * hash) + WANTING_FIELD_NUMBER;
        hash = (53 * hash) + getWanting().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static trade.Trade.WithBank parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static trade.Trade.WithBank parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static trade.Trade.WithBank parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static trade.Trade.WithBank parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static trade.Trade.WithBank parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static trade.Trade.WithBank parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static trade.Trade.WithBank parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static trade.Trade.WithBank parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static trade.Trade.WithBank parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static trade.Trade.WithBank parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(trade.Trade.WithBank prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code trade.WithBank}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:trade.WithBank)
        trade.Trade.WithBankOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return trade.Trade.internal_static_trade_WithBank_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return trade.Trade.internal_static_trade_WithBank_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                trade.Trade.WithBank.class, trade.Trade.WithBank.Builder.class);
      }

      // Construct using trade.Trade.WithBank.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (offeringBuilder_ == null) {
          offering_ = null;
        } else {
          offering_ = null;
          offeringBuilder_ = null;
        }
        if (wantingBuilder_ == null) {
          wanting_ = null;
        } else {
          wanting_ = null;
          wantingBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return trade.Trade.internal_static_trade_WithBank_descriptor;
      }

      public trade.Trade.WithBank getDefaultInstanceForType() {
        return trade.Trade.WithBank.getDefaultInstance();
      }

      public trade.Trade.WithBank build() {
        trade.Trade.WithBank result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public trade.Trade.WithBank buildPartial() {
        trade.Trade.WithBank result = new trade.Trade.WithBank(this);
        if (offeringBuilder_ == null) {
          result.offering_ = offering_;
        } else {
          result.offering_ = offeringBuilder_.build();
        }
        if (wantingBuilder_ == null) {
          result.wanting_ = wanting_;
        } else {
          result.wanting_ = wantingBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof trade.Trade.WithBank) {
          return mergeFrom((trade.Trade.WithBank)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(trade.Trade.WithBank other) {
        if (other == trade.Trade.WithBank.getDefaultInstance()) return this;
        if (other.hasOffering()) {
          mergeOffering(other.getOffering());
        }
        if (other.hasWanting()) {
          mergeWanting(other.getWanting());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        trade.Trade.WithBank parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (trade.Trade.WithBank) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private resource.Resource.Counts offering_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          resource.Resource.Counts, resource.Resource.Counts.Builder, resource.Resource.CountsOrBuilder> offeringBuilder_;
      /**
       * <code>.resource.Counts offering = 1;</code>
       */
      public boolean hasOffering() {
        return offeringBuilder_ != null || offering_ != null;
      }
      /**
       * <code>.resource.Counts offering = 1;</code>
       */
      public resource.Resource.Counts getOffering() {
        if (offeringBuilder_ == null) {
          return offering_ == null ? resource.Resource.Counts.getDefaultInstance() : offering_;
        } else {
          return offeringBuilder_.getMessage();
        }
      }
      /**
       * <code>.resource.Counts offering = 1;</code>
       */
      public Builder setOffering(resource.Resource.Counts value) {
        if (offeringBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          offering_ = value;
          onChanged();
        } else {
          offeringBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.resource.Counts offering = 1;</code>
       */
      public Builder setOffering(
          resource.Resource.Counts.Builder builderForValue) {
        if (offeringBuilder_ == null) {
          offering_ = builderForValue.build();
          onChanged();
        } else {
          offeringBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.resource.Counts offering = 1;</code>
       */
      public Builder mergeOffering(resource.Resource.Counts value) {
        if (offeringBuilder_ == null) {
          if (offering_ != null) {
            offering_ =
              resource.Resource.Counts.newBuilder(offering_).mergeFrom(value).buildPartial();
          } else {
            offering_ = value;
          }
          onChanged();
        } else {
          offeringBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.resource.Counts offering = 1;</code>
       */
      public Builder clearOffering() {
        if (offeringBuilder_ == null) {
          offering_ = null;
          onChanged();
        } else {
          offering_ = null;
          offeringBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.resource.Counts offering = 1;</code>
       */
      public resource.Resource.Counts.Builder getOfferingBuilder() {
        
        onChanged();
        return getOfferingFieldBuilder().getBuilder();
      }
      /**
       * <code>.resource.Counts offering = 1;</code>
       */
      public resource.Resource.CountsOrBuilder getOfferingOrBuilder() {
        if (offeringBuilder_ != null) {
          return offeringBuilder_.getMessageOrBuilder();
        } else {
          return offering_ == null ?
              resource.Resource.Counts.getDefaultInstance() : offering_;
        }
      }
      /**
       * <code>.resource.Counts offering = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          resource.Resource.Counts, resource.Resource.Counts.Builder, resource.Resource.CountsOrBuilder> 
          getOfferingFieldBuilder() {
        if (offeringBuilder_ == null) {
          offeringBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              resource.Resource.Counts, resource.Resource.Counts.Builder, resource.Resource.CountsOrBuilder>(
                  getOffering(),
                  getParentForChildren(),
                  isClean());
          offering_ = null;
        }
        return offeringBuilder_;
      }

      private resource.Resource.Counts wanting_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          resource.Resource.Counts, resource.Resource.Counts.Builder, resource.Resource.CountsOrBuilder> wantingBuilder_;
      /**
       * <code>.resource.Counts wanting = 2;</code>
       */
      public boolean hasWanting() {
        return wantingBuilder_ != null || wanting_ != null;
      }
      /**
       * <code>.resource.Counts wanting = 2;</code>
       */
      public resource.Resource.Counts getWanting() {
        if (wantingBuilder_ == null) {
          return wanting_ == null ? resource.Resource.Counts.getDefaultInstance() : wanting_;
        } else {
          return wantingBuilder_.getMessage();
        }
      }
      /**
       * <code>.resource.Counts wanting = 2;</code>
       */
      public Builder setWanting(resource.Resource.Counts value) {
        if (wantingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          wanting_ = value;
          onChanged();
        } else {
          wantingBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.resource.Counts wanting = 2;</code>
       */
      public Builder setWanting(
          resource.Resource.Counts.Builder builderForValue) {
        if (wantingBuilder_ == null) {
          wanting_ = builderForValue.build();
          onChanged();
        } else {
          wantingBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.resource.Counts wanting = 2;</code>
       */
      public Builder mergeWanting(resource.Resource.Counts value) {
        if (wantingBuilder_ == null) {
          if (wanting_ != null) {
            wanting_ =
              resource.Resource.Counts.newBuilder(wanting_).mergeFrom(value).buildPartial();
          } else {
            wanting_ = value;
          }
          onChanged();
        } else {
          wantingBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.resource.Counts wanting = 2;</code>
       */
      public Builder clearWanting() {
        if (wantingBuilder_ == null) {
          wanting_ = null;
          onChanged();
        } else {
          wanting_ = null;
          wantingBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.resource.Counts wanting = 2;</code>
       */
      public resource.Resource.Counts.Builder getWantingBuilder() {
        
        onChanged();
        return getWantingFieldBuilder().getBuilder();
      }
      /**
       * <code>.resource.Counts wanting = 2;</code>
       */
      public resource.Resource.CountsOrBuilder getWantingOrBuilder() {
        if (wantingBuilder_ != null) {
          return wantingBuilder_.getMessageOrBuilder();
        } else {
          return wanting_ == null ?
              resource.Resource.Counts.getDefaultInstance() : wanting_;
        }
      }
      /**
       * <code>.resource.Counts wanting = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          resource.Resource.Counts, resource.Resource.Counts.Builder, resource.Resource.CountsOrBuilder> 
          getWantingFieldBuilder() {
        if (wantingBuilder_ == null) {
          wantingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              resource.Resource.Counts, resource.Resource.Counts.Builder, resource.Resource.CountsOrBuilder>(
                  getWanting(),
                  getParentForChildren(),
                  isClean());
          wanting_ = null;
        }
        return wantingBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:trade.WithBank)
    }

    // @@protoc_insertion_point(class_scope:trade.WithBank)
    private static final trade.Trade.WithBank DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new trade.Trade.WithBank();
    }

    public static trade.Trade.WithBank getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WithBank>
        PARSER = new com.google.protobuf.AbstractParser<WithBank>() {
      public WithBank parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new WithBank(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WithBank> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WithBank> getParserForType() {
      return PARSER;
    }

    public trade.Trade.WithBank getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WithPlayerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:trade.WithPlayer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.board.Player other = 1;</code>
     */
    boolean hasOther();
    /**
     * <code>.board.Player other = 1;</code>
     */
    board.Board.Player getOther();
    /**
     * <code>.board.Player other = 1;</code>
     */
    board.Board.PlayerOrBuilder getOtherOrBuilder();

    /**
     * <code>.resource.Counts offering = 2;</code>
     */
    boolean hasOffering();
    /**
     * <code>.resource.Counts offering = 2;</code>
     */
    resource.Resource.Counts getOffering();
    /**
     * <code>.resource.Counts offering = 2;</code>
     */
    resource.Resource.CountsOrBuilder getOfferingOrBuilder();

    /**
     * <code>.resource.Counts wanting = 3;</code>
     */
    boolean hasWanting();
    /**
     * <code>.resource.Counts wanting = 3;</code>
     */
    resource.Resource.Counts getWanting();
    /**
     * <code>.resource.Counts wanting = 3;</code>
     */
    resource.Resource.CountsOrBuilder getWantingOrBuilder();
  }
  /**
   * Protobuf type {@code trade.WithPlayer}
   */
  public  static final class WithPlayer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:trade.WithPlayer)
      WithPlayerOrBuilder {
    // Use WithPlayer.newBuilder() to construct.
    private WithPlayer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WithPlayer() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private WithPlayer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              board.Board.Player.Builder subBuilder = null;
              if (other_ != null) {
                subBuilder = other_.toBuilder();
              }
              other_ = input.readMessage(board.Board.Player.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(other_);
                other_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              resource.Resource.Counts.Builder subBuilder = null;
              if (offering_ != null) {
                subBuilder = offering_.toBuilder();
              }
              offering_ = input.readMessage(resource.Resource.Counts.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(offering_);
                offering_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              resource.Resource.Counts.Builder subBuilder = null;
              if (wanting_ != null) {
                subBuilder = wanting_.toBuilder();
              }
              wanting_ = input.readMessage(resource.Resource.Counts.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(wanting_);
                wanting_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return trade.Trade.internal_static_trade_WithPlayer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return trade.Trade.internal_static_trade_WithPlayer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              trade.Trade.WithPlayer.class, trade.Trade.WithPlayer.Builder.class);
    }

    public static final int OTHER_FIELD_NUMBER = 1;
    private board.Board.Player other_;
    /**
     * <code>.board.Player other = 1;</code>
     */
    public boolean hasOther() {
      return other_ != null;
    }
    /**
     * <code>.board.Player other = 1;</code>
     */
    public board.Board.Player getOther() {
      return other_ == null ? board.Board.Player.getDefaultInstance() : other_;
    }
    /**
     * <code>.board.Player other = 1;</code>
     */
    public board.Board.PlayerOrBuilder getOtherOrBuilder() {
      return getOther();
    }

    public static final int OFFERING_FIELD_NUMBER = 2;
    private resource.Resource.Counts offering_;
    /**
     * <code>.resource.Counts offering = 2;</code>
     */
    public boolean hasOffering() {
      return offering_ != null;
    }
    /**
     * <code>.resource.Counts offering = 2;</code>
     */
    public resource.Resource.Counts getOffering() {
      return offering_ == null ? resource.Resource.Counts.getDefaultInstance() : offering_;
    }
    /**
     * <code>.resource.Counts offering = 2;</code>
     */
    public resource.Resource.CountsOrBuilder getOfferingOrBuilder() {
      return getOffering();
    }

    public static final int WANTING_FIELD_NUMBER = 3;
    private resource.Resource.Counts wanting_;
    /**
     * <code>.resource.Counts wanting = 3;</code>
     */
    public boolean hasWanting() {
      return wanting_ != null;
    }
    /**
     * <code>.resource.Counts wanting = 3;</code>
     */
    public resource.Resource.Counts getWanting() {
      return wanting_ == null ? resource.Resource.Counts.getDefaultInstance() : wanting_;
    }
    /**
     * <code>.resource.Counts wanting = 3;</code>
     */
    public resource.Resource.CountsOrBuilder getWantingOrBuilder() {
      return getWanting();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (other_ != null) {
        output.writeMessage(1, getOther());
      }
      if (offering_ != null) {
        output.writeMessage(2, getOffering());
      }
      if (wanting_ != null) {
        output.writeMessage(3, getWanting());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (other_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getOther());
      }
      if (offering_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getOffering());
      }
      if (wanting_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getWanting());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof trade.Trade.WithPlayer)) {
        return super.equals(obj);
      }
      trade.Trade.WithPlayer other = (trade.Trade.WithPlayer) obj;

      boolean result = true;
      result = result && (hasOther() == other.hasOther());
      if (hasOther()) {
        result = result && getOther()
            .equals(other.getOther());
      }
      result = result && (hasOffering() == other.hasOffering());
      if (hasOffering()) {
        result = result && getOffering()
            .equals(other.getOffering());
      }
      result = result && (hasWanting() == other.hasWanting());
      if (hasWanting()) {
        result = result && getWanting()
            .equals(other.getWanting());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasOther()) {
        hash = (37 * hash) + OTHER_FIELD_NUMBER;
        hash = (53 * hash) + getOther().hashCode();
      }
      if (hasOffering()) {
        hash = (37 * hash) + OFFERING_FIELD_NUMBER;
        hash = (53 * hash) + getOffering().hashCode();
      }
      if (hasWanting()) {
        hash = (37 * hash) + WANTING_FIELD_NUMBER;
        hash = (53 * hash) + getWanting().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static trade.Trade.WithPlayer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static trade.Trade.WithPlayer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static trade.Trade.WithPlayer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static trade.Trade.WithPlayer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static trade.Trade.WithPlayer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static trade.Trade.WithPlayer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static trade.Trade.WithPlayer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static trade.Trade.WithPlayer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static trade.Trade.WithPlayer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static trade.Trade.WithPlayer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(trade.Trade.WithPlayer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code trade.WithPlayer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:trade.WithPlayer)
        trade.Trade.WithPlayerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return trade.Trade.internal_static_trade_WithPlayer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return trade.Trade.internal_static_trade_WithPlayer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                trade.Trade.WithPlayer.class, trade.Trade.WithPlayer.Builder.class);
      }

      // Construct using trade.Trade.WithPlayer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (otherBuilder_ == null) {
          other_ = null;
        } else {
          other_ = null;
          otherBuilder_ = null;
        }
        if (offeringBuilder_ == null) {
          offering_ = null;
        } else {
          offering_ = null;
          offeringBuilder_ = null;
        }
        if (wantingBuilder_ == null) {
          wanting_ = null;
        } else {
          wanting_ = null;
          wantingBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return trade.Trade.internal_static_trade_WithPlayer_descriptor;
      }

      public trade.Trade.WithPlayer getDefaultInstanceForType() {
        return trade.Trade.WithPlayer.getDefaultInstance();
      }

      public trade.Trade.WithPlayer build() {
        trade.Trade.WithPlayer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public trade.Trade.WithPlayer buildPartial() {
        trade.Trade.WithPlayer result = new trade.Trade.WithPlayer(this);
        if (otherBuilder_ == null) {
          result.other_ = other_;
        } else {
          result.other_ = otherBuilder_.build();
        }
        if (offeringBuilder_ == null) {
          result.offering_ = offering_;
        } else {
          result.offering_ = offeringBuilder_.build();
        }
        if (wantingBuilder_ == null) {
          result.wanting_ = wanting_;
        } else {
          result.wanting_ = wantingBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof trade.Trade.WithPlayer) {
          return mergeFrom((trade.Trade.WithPlayer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(trade.Trade.WithPlayer other) {
        if (other == trade.Trade.WithPlayer.getDefaultInstance()) return this;
        if (other.hasOther()) {
          mergeOther(other.getOther());
        }
        if (other.hasOffering()) {
          mergeOffering(other.getOffering());
        }
        if (other.hasWanting()) {
          mergeWanting(other.getWanting());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        trade.Trade.WithPlayer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (trade.Trade.WithPlayer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private board.Board.Player other_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          board.Board.Player, board.Board.Player.Builder, board.Board.PlayerOrBuilder> otherBuilder_;
      /**
       * <code>.board.Player other = 1;</code>
       */
      public boolean hasOther() {
        return otherBuilder_ != null || other_ != null;
      }
      /**
       * <code>.board.Player other = 1;</code>
       */
      public board.Board.Player getOther() {
        if (otherBuilder_ == null) {
          return other_ == null ? board.Board.Player.getDefaultInstance() : other_;
        } else {
          return otherBuilder_.getMessage();
        }
      }
      /**
       * <code>.board.Player other = 1;</code>
       */
      public Builder setOther(board.Board.Player value) {
        if (otherBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          other_ = value;
          onChanged();
        } else {
          otherBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.board.Player other = 1;</code>
       */
      public Builder setOther(
          board.Board.Player.Builder builderForValue) {
        if (otherBuilder_ == null) {
          other_ = builderForValue.build();
          onChanged();
        } else {
          otherBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.board.Player other = 1;</code>
       */
      public Builder mergeOther(board.Board.Player value) {
        if (otherBuilder_ == null) {
          if (other_ != null) {
            other_ =
              board.Board.Player.newBuilder(other_).mergeFrom(value).buildPartial();
          } else {
            other_ = value;
          }
          onChanged();
        } else {
          otherBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.board.Player other = 1;</code>
       */
      public Builder clearOther() {
        if (otherBuilder_ == null) {
          other_ = null;
          onChanged();
        } else {
          other_ = null;
          otherBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.board.Player other = 1;</code>
       */
      public board.Board.Player.Builder getOtherBuilder() {
        
        onChanged();
        return getOtherFieldBuilder().getBuilder();
      }
      /**
       * <code>.board.Player other = 1;</code>
       */
      public board.Board.PlayerOrBuilder getOtherOrBuilder() {
        if (otherBuilder_ != null) {
          return otherBuilder_.getMessageOrBuilder();
        } else {
          return other_ == null ?
              board.Board.Player.getDefaultInstance() : other_;
        }
      }
      /**
       * <code>.board.Player other = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          board.Board.Player, board.Board.Player.Builder, board.Board.PlayerOrBuilder> 
          getOtherFieldBuilder() {
        if (otherBuilder_ == null) {
          otherBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              board.Board.Player, board.Board.Player.Builder, board.Board.PlayerOrBuilder>(
                  getOther(),
                  getParentForChildren(),
                  isClean());
          other_ = null;
        }
        return otherBuilder_;
      }

      private resource.Resource.Counts offering_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          resource.Resource.Counts, resource.Resource.Counts.Builder, resource.Resource.CountsOrBuilder> offeringBuilder_;
      /**
       * <code>.resource.Counts offering = 2;</code>
       */
      public boolean hasOffering() {
        return offeringBuilder_ != null || offering_ != null;
      }
      /**
       * <code>.resource.Counts offering = 2;</code>
       */
      public resource.Resource.Counts getOffering() {
        if (offeringBuilder_ == null) {
          return offering_ == null ? resource.Resource.Counts.getDefaultInstance() : offering_;
        } else {
          return offeringBuilder_.getMessage();
        }
      }
      /**
       * <code>.resource.Counts offering = 2;</code>
       */
      public Builder setOffering(resource.Resource.Counts value) {
        if (offeringBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          offering_ = value;
          onChanged();
        } else {
          offeringBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.resource.Counts offering = 2;</code>
       */
      public Builder setOffering(
          resource.Resource.Counts.Builder builderForValue) {
        if (offeringBuilder_ == null) {
          offering_ = builderForValue.build();
          onChanged();
        } else {
          offeringBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.resource.Counts offering = 2;</code>
       */
      public Builder mergeOffering(resource.Resource.Counts value) {
        if (offeringBuilder_ == null) {
          if (offering_ != null) {
            offering_ =
              resource.Resource.Counts.newBuilder(offering_).mergeFrom(value).buildPartial();
          } else {
            offering_ = value;
          }
          onChanged();
        } else {
          offeringBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.resource.Counts offering = 2;</code>
       */
      public Builder clearOffering() {
        if (offeringBuilder_ == null) {
          offering_ = null;
          onChanged();
        } else {
          offering_ = null;
          offeringBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.resource.Counts offering = 2;</code>
       */
      public resource.Resource.Counts.Builder getOfferingBuilder() {
        
        onChanged();
        return getOfferingFieldBuilder().getBuilder();
      }
      /**
       * <code>.resource.Counts offering = 2;</code>
       */
      public resource.Resource.CountsOrBuilder getOfferingOrBuilder() {
        if (offeringBuilder_ != null) {
          return offeringBuilder_.getMessageOrBuilder();
        } else {
          return offering_ == null ?
              resource.Resource.Counts.getDefaultInstance() : offering_;
        }
      }
      /**
       * <code>.resource.Counts offering = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          resource.Resource.Counts, resource.Resource.Counts.Builder, resource.Resource.CountsOrBuilder> 
          getOfferingFieldBuilder() {
        if (offeringBuilder_ == null) {
          offeringBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              resource.Resource.Counts, resource.Resource.Counts.Builder, resource.Resource.CountsOrBuilder>(
                  getOffering(),
                  getParentForChildren(),
                  isClean());
          offering_ = null;
        }
        return offeringBuilder_;
      }

      private resource.Resource.Counts wanting_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          resource.Resource.Counts, resource.Resource.Counts.Builder, resource.Resource.CountsOrBuilder> wantingBuilder_;
      /**
       * <code>.resource.Counts wanting = 3;</code>
       */
      public boolean hasWanting() {
        return wantingBuilder_ != null || wanting_ != null;
      }
      /**
       * <code>.resource.Counts wanting = 3;</code>
       */
      public resource.Resource.Counts getWanting() {
        if (wantingBuilder_ == null) {
          return wanting_ == null ? resource.Resource.Counts.getDefaultInstance() : wanting_;
        } else {
          return wantingBuilder_.getMessage();
        }
      }
      /**
       * <code>.resource.Counts wanting = 3;</code>
       */
      public Builder setWanting(resource.Resource.Counts value) {
        if (wantingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          wanting_ = value;
          onChanged();
        } else {
          wantingBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.resource.Counts wanting = 3;</code>
       */
      public Builder setWanting(
          resource.Resource.Counts.Builder builderForValue) {
        if (wantingBuilder_ == null) {
          wanting_ = builderForValue.build();
          onChanged();
        } else {
          wantingBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.resource.Counts wanting = 3;</code>
       */
      public Builder mergeWanting(resource.Resource.Counts value) {
        if (wantingBuilder_ == null) {
          if (wanting_ != null) {
            wanting_ =
              resource.Resource.Counts.newBuilder(wanting_).mergeFrom(value).buildPartial();
          } else {
            wanting_ = value;
          }
          onChanged();
        } else {
          wantingBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.resource.Counts wanting = 3;</code>
       */
      public Builder clearWanting() {
        if (wantingBuilder_ == null) {
          wanting_ = null;
          onChanged();
        } else {
          wanting_ = null;
          wantingBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.resource.Counts wanting = 3;</code>
       */
      public resource.Resource.Counts.Builder getWantingBuilder() {
        
        onChanged();
        return getWantingFieldBuilder().getBuilder();
      }
      /**
       * <code>.resource.Counts wanting = 3;</code>
       */
      public resource.Resource.CountsOrBuilder getWantingOrBuilder() {
        if (wantingBuilder_ != null) {
          return wantingBuilder_.getMessageOrBuilder();
        } else {
          return wanting_ == null ?
              resource.Resource.Counts.getDefaultInstance() : wanting_;
        }
      }
      /**
       * <code>.resource.Counts wanting = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          resource.Resource.Counts, resource.Resource.Counts.Builder, resource.Resource.CountsOrBuilder> 
          getWantingFieldBuilder() {
        if (wantingBuilder_ == null) {
          wantingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              resource.Resource.Counts, resource.Resource.Counts.Builder, resource.Resource.CountsOrBuilder>(
                  getWanting(),
                  getParentForChildren(),
                  isClean());
          wanting_ = null;
        }
        return wantingBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:trade.WithPlayer)
    }

    // @@protoc_insertion_point(class_scope:trade.WithPlayer)
    private static final trade.Trade.WithPlayer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new trade.Trade.WithPlayer();
    }

    public static trade.Trade.WithPlayer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WithPlayer>
        PARSER = new com.google.protobuf.AbstractParser<WithPlayer>() {
      public WithPlayer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new WithPlayer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WithPlayer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WithPlayer> getParserForType() {
      return PARSER;
    }

    public trade.Trade.WithPlayer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trade_Kind_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trade_Kind_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trade_WithBank_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trade_WithBank_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trade_WithPlayer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trade_WithPlayer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021trade/trade.proto\022\005trade\032\027resource/res" +
      "ource.proto\032\021board/board.proto\"U\n\004Kind\022#" +
      "\n\006player\030\001 \001(\0132\021.trade.WithPlayerH\000\022\037\n\004b" +
      "ank\030\002 \001(\0132\017.trade.WithBankH\000B\007\n\005trade\"Q\n" +
      "\010WithBank\022\"\n\010offering\030\001 \001(\0132\020.resource.C" +
      "ounts\022!\n\007wanting\030\002 \001(\0132\020.resource.Counts" +
      "\"q\n\nWithPlayer\022\034\n\005other\030\001 \001(\0132\r.board.Pl" +
      "ayer\022\"\n\010offering\030\002 \001(\0132\020.resource.Counts" +
      "\022!\n\007wanting\030\003 \001(\0132\020.resource.Counts*\"\n\010R" +
      "esponse\022\n\n\006REJECT\020\000\022\n\n\006ACCEPT\020\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          resource.Resource.getDescriptor(),
          board.Board.getDescriptor(),
        }, assigner);
    internal_static_trade_Kind_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_trade_Kind_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trade_Kind_descriptor,
        new java.lang.String[] { "Player", "Bank", "Trade", });
    internal_static_trade_WithBank_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_trade_WithBank_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trade_WithBank_descriptor,
        new java.lang.String[] { "Offering", "Wanting", });
    internal_static_trade_WithPlayer_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_trade_WithPlayer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trade_WithPlayer_descriptor,
        new java.lang.String[] { "Other", "Offering", "Wanting", });
    resource.Resource.getDescriptor();
    board.Board.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
