// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resource/resource.proto

package intergroup.resource;

public final class Resource {
  private Resource() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code intergroup.resource.Kind}
   */
  public enum Kind
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GENERIC = 0;</code>
     */
    GENERIC(0),
    /**
     * <code>BRICK = 1;</code>
     */
    BRICK(1),
    /**
     * <code>LUMBER = 2;</code>
     */
    LUMBER(2),
    /**
     * <code>WOOL = 3;</code>
     */
    WOOL(3),
    /**
     * <code>GRAIN = 4;</code>
     */
    GRAIN(4),
    /**
     * <code>ORE = 5;</code>
     */
    ORE(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>GENERIC = 0;</code>
     */
    public static final int GENERIC_VALUE = 0;
    /**
     * <code>BRICK = 1;</code>
     */
    public static final int BRICK_VALUE = 1;
    /**
     * <code>LUMBER = 2;</code>
     */
    public static final int LUMBER_VALUE = 2;
    /**
     * <code>WOOL = 3;</code>
     */
    public static final int WOOL_VALUE = 3;
    /**
     * <code>GRAIN = 4;</code>
     */
    public static final int GRAIN_VALUE = 4;
    /**
     * <code>ORE = 5;</code>
     */
    public static final int ORE_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Kind valueOf(int value) {
      return forNumber(value);
    }

    public static Kind forNumber(int value) {
      switch (value) {
        case 0: return GENERIC;
        case 1: return BRICK;
        case 2: return LUMBER;
        case 3: return WOOL;
        case 4: return GRAIN;
        case 5: return ORE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Kind>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Kind> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Kind>() {
            public Kind findValueByNumber(int number) {
              return Kind.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return intergroup.resource.Resource.getDescriptor().getEnumTypes().get(0);
    }

    private static final Kind[] VALUES = values();

    public static Kind valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Kind(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:intergroup.resource.Kind)
  }

  public interface CountsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:intergroup.resource.Counts)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 brick = 1;</code>
     */
    int getBrick();

    /**
     * <code>int32 lumber = 2;</code>
     */
    int getLumber();

    /**
     * <code>int32 wool = 3;</code>
     */
    int getWool();

    /**
     * <code>int32 grain = 4;</code>
     */
    int getGrain();

    /**
     * <code>int32 ore = 5;</code>
     */
    int getOre();
  }
  /**
   * Protobuf type {@code intergroup.resource.Counts}
   */
  public  static final class Counts extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:intergroup.resource.Counts)
      CountsOrBuilder {
    // Use Counts.newBuilder() to construct.
    private Counts(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Counts() {
      brick_ = 0;
      lumber_ = 0;
      wool_ = 0;
      grain_ = 0;
      ore_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Counts(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              brick_ = input.readInt32();
              break;
            }
            case 16: {

              lumber_ = input.readInt32();
              break;
            }
            case 24: {

              wool_ = input.readInt32();
              break;
            }
            case 32: {

              grain_ = input.readInt32();
              break;
            }
            case 40: {

              ore_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return intergroup.resource.Resource.internal_static_intergroup_resource_Counts_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return intergroup.resource.Resource.internal_static_intergroup_resource_Counts_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              intergroup.resource.Resource.Counts.class, intergroup.resource.Resource.Counts.Builder.class);
    }

    public static final int BRICK_FIELD_NUMBER = 1;
    private int brick_;
    /**
     * <code>int32 brick = 1;</code>
     */
    public int getBrick() {
      return brick_;
    }

    public static final int LUMBER_FIELD_NUMBER = 2;
    private int lumber_;
    /**
     * <code>int32 lumber = 2;</code>
     */
    public int getLumber() {
      return lumber_;
    }

    public static final int WOOL_FIELD_NUMBER = 3;
    private int wool_;
    /**
     * <code>int32 wool = 3;</code>
     */
    public int getWool() {
      return wool_;
    }

    public static final int GRAIN_FIELD_NUMBER = 4;
    private int grain_;
    /**
     * <code>int32 grain = 4;</code>
     */
    public int getGrain() {
      return grain_;
    }

    public static final int ORE_FIELD_NUMBER = 5;
    private int ore_;
    /**
     * <code>int32 ore = 5;</code>
     */
    public int getOre() {
      return ore_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (brick_ != 0) {
        output.writeInt32(1, brick_);
      }
      if (lumber_ != 0) {
        output.writeInt32(2, lumber_);
      }
      if (wool_ != 0) {
        output.writeInt32(3, wool_);
      }
      if (grain_ != 0) {
        output.writeInt32(4, grain_);
      }
      if (ore_ != 0) {
        output.writeInt32(5, ore_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (brick_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, brick_);
      }
      if (lumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, lumber_);
      }
      if (wool_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, wool_);
      }
      if (grain_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, grain_);
      }
      if (ore_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, ore_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof intergroup.resource.Resource.Counts)) {
        return super.equals(obj);
      }
      intergroup.resource.Resource.Counts other = (intergroup.resource.Resource.Counts) obj;

      boolean result = true;
      result = result && (getBrick()
          == other.getBrick());
      result = result && (getLumber()
          == other.getLumber());
      result = result && (getWool()
          == other.getWool());
      result = result && (getGrain()
          == other.getGrain());
      result = result && (getOre()
          == other.getOre());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BRICK_FIELD_NUMBER;
      hash = (53 * hash) + getBrick();
      hash = (37 * hash) + LUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getLumber();
      hash = (37 * hash) + WOOL_FIELD_NUMBER;
      hash = (53 * hash) + getWool();
      hash = (37 * hash) + GRAIN_FIELD_NUMBER;
      hash = (53 * hash) + getGrain();
      hash = (37 * hash) + ORE_FIELD_NUMBER;
      hash = (53 * hash) + getOre();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static intergroup.resource.Resource.Counts parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static intergroup.resource.Resource.Counts parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static intergroup.resource.Resource.Counts parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static intergroup.resource.Resource.Counts parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static intergroup.resource.Resource.Counts parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static intergroup.resource.Resource.Counts parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static intergroup.resource.Resource.Counts parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static intergroup.resource.Resource.Counts parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static intergroup.resource.Resource.Counts parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static intergroup.resource.Resource.Counts parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(intergroup.resource.Resource.Counts prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code intergroup.resource.Counts}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:intergroup.resource.Counts)
        intergroup.resource.Resource.CountsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return intergroup.resource.Resource.internal_static_intergroup_resource_Counts_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return intergroup.resource.Resource.internal_static_intergroup_resource_Counts_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                intergroup.resource.Resource.Counts.class, intergroup.resource.Resource.Counts.Builder.class);
      }

      // Construct using intergroup.resource.Resource.Counts.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        brick_ = 0;

        lumber_ = 0;

        wool_ = 0;

        grain_ = 0;

        ore_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return intergroup.resource.Resource.internal_static_intergroup_resource_Counts_descriptor;
      }

      public intergroup.resource.Resource.Counts getDefaultInstanceForType() {
        return intergroup.resource.Resource.Counts.getDefaultInstance();
      }

      public intergroup.resource.Resource.Counts build() {
        intergroup.resource.Resource.Counts result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public intergroup.resource.Resource.Counts buildPartial() {
        intergroup.resource.Resource.Counts result = new intergroup.resource.Resource.Counts(this);
        result.brick_ = brick_;
        result.lumber_ = lumber_;
        result.wool_ = wool_;
        result.grain_ = grain_;
        result.ore_ = ore_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof intergroup.resource.Resource.Counts) {
          return mergeFrom((intergroup.resource.Resource.Counts)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(intergroup.resource.Resource.Counts other) {
        if (other == intergroup.resource.Resource.Counts.getDefaultInstance()) return this;
        if (other.getBrick() != 0) {
          setBrick(other.getBrick());
        }
        if (other.getLumber() != 0) {
          setLumber(other.getLumber());
        }
        if (other.getWool() != 0) {
          setWool(other.getWool());
        }
        if (other.getGrain() != 0) {
          setGrain(other.getGrain());
        }
        if (other.getOre() != 0) {
          setOre(other.getOre());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        intergroup.resource.Resource.Counts parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (intergroup.resource.Resource.Counts) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int brick_ ;
      /**
       * <code>int32 brick = 1;</code>
       */
      public int getBrick() {
        return brick_;
      }
      /**
       * <code>int32 brick = 1;</code>
       */
      public Builder setBrick(int value) {
        
        brick_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 brick = 1;</code>
       */
      public Builder clearBrick() {
        
        brick_ = 0;
        onChanged();
        return this;
      }

      private int lumber_ ;
      /**
       * <code>int32 lumber = 2;</code>
       */
      public int getLumber() {
        return lumber_;
      }
      /**
       * <code>int32 lumber = 2;</code>
       */
      public Builder setLumber(int value) {
        
        lumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 lumber = 2;</code>
       */
      public Builder clearLumber() {
        
        lumber_ = 0;
        onChanged();
        return this;
      }

      private int wool_ ;
      /**
       * <code>int32 wool = 3;</code>
       */
      public int getWool() {
        return wool_;
      }
      /**
       * <code>int32 wool = 3;</code>
       */
      public Builder setWool(int value) {
        
        wool_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 wool = 3;</code>
       */
      public Builder clearWool() {
        
        wool_ = 0;
        onChanged();
        return this;
      }

      private int grain_ ;
      /**
       * <code>int32 grain = 4;</code>
       */
      public int getGrain() {
        return grain_;
      }
      /**
       * <code>int32 grain = 4;</code>
       */
      public Builder setGrain(int value) {
        
        grain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 grain = 4;</code>
       */
      public Builder clearGrain() {
        
        grain_ = 0;
        onChanged();
        return this;
      }

      private int ore_ ;
      /**
       * <code>int32 ore = 5;</code>
       */
      public int getOre() {
        return ore_;
      }
      /**
       * <code>int32 ore = 5;</code>
       */
      public Builder setOre(int value) {
        
        ore_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 ore = 5;</code>
       */
      public Builder clearOre() {
        
        ore_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:intergroup.resource.Counts)
    }

    // @@protoc_insertion_point(class_scope:intergroup.resource.Counts)
    private static final intergroup.resource.Resource.Counts DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new intergroup.resource.Resource.Counts();
    }

    public static intergroup.resource.Resource.Counts getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Counts>
        PARSER = new com.google.protobuf.AbstractParser<Counts>() {
      public Counts parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Counts(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Counts> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Counts> getParserForType() {
      return PARSER;
    }

    public intergroup.resource.Resource.Counts getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_intergroup_resource_Counts_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_intergroup_resource_Counts_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027resource/resource.proto\022\023intergroup.re" +
      "source\"Q\n\006Counts\022\r\n\005brick\030\001 \001(\005\022\016\n\006lumbe" +
      "r\030\002 \001(\005\022\014\n\004wool\030\003 \001(\005\022\r\n\005grain\030\004 \001(\005\022\013\n\003" +
      "ore\030\005 \001(\005*H\n\004Kind\022\013\n\007GENERIC\020\000\022\t\n\005BRICK\020" +
      "\001\022\n\n\006LUMBER\020\002\022\010\n\004WOOL\020\003\022\t\n\005GRAIN\020\004\022\007\n\003OR" +
      "E\020\005b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_intergroup_resource_Counts_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_intergroup_resource_Counts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_intergroup_resource_Counts_descriptor,
        new java.lang.String[] { "Brick", "Lumber", "Wool", "Grain", "Ore", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
